export const englishGallery = {
  title: "Quest Gallery",
  navigation: "Quest gallery",
  back: "Back to game",
  overview: "Back to overview",
  search: "Search quests…",
  filter: "Filter quests",
  filters: "Filters",
  filtersTitle: "Quest filters",
  filtersDescription:
    "Choose several values inside a group. Quests match across all selected groups.",
  applyFilters: "Apply filters",
  clearFilters: "Clear filters",
  statusFilter: "Progress",
  moodFilter: "Mood",
  genreFilter: "Genre",
  playStyleFilter: "Play style",
  gameFilter: "Game",
  anyGameFilter: "Any game",
  tagFilter: "Tags",
  all: "All",
  found: "Found quests",
  favorites: "Your favorites",
  completed: "Completed",
  uncompleted: "Uncompleted",
  browse: "Scroll or drag to browse quests",
  details: "Quest details and lifetime statistics",
  unknown: "Unknown",
  unknownCard: "You haven't drawn this card yet.",
  questCompleted: "Quest completed",
  notCompleted: "Not completed yet",
  favorite: "Favorite",
  start: "Start quest",
  repeat: "Repeat quest",
  repeated: "Quest repeated",
  coinsEarned: "Coins earned",
  lastPlayed: "Last played",
  longest: "Longest session",
  personalBest: "Personal best",
  activeQuest: "Finish or cancel your current quest before starting another.",
  empty: "No quests match your filters.",
};
export const germanGallery: Record<keyof typeof englishGallery, string> = {
  title: "Quests-Galerie",
  navigation: "Quests-Galerie",
  back: "Zurück zum Spiel",
  overview: "Zurück zur Übersicht",
  search: "Quests durchsuchen…",
  filter: "Quests filtern",
  filters: "Filter",
  filtersTitle: "Quest-Filter",
  filtersDescription:
    "Wähle mehrere Werte innerhalb einer Gruppe. Eine Quest muss zu allen gewählten Gruppen passen.",
  applyFilters: "Filter anwenden",
  clearFilters: "Filter zurücksetzen",
  statusFilter: "Fortschritt",
  moodFilter: "Stimmung",
  genreFilter: "Genre",
  playStyleFilter: "Modus",
  gameFilter: "Spiel",
  anyGameFilter: "Beliebiges Spiel",
  tagFilter: "Tags",
  all: "Alle Quests",
  found: "Gefundene Quests",
  favorites: "Deine Favoriten",
  completed: "Abgeschlossen",
  uncompleted: "Noch offen",
  browse: "Scrollen oder ziehen, um Quests anzusehen",
  details: "Quest-Details und gesamte Statistik",
  unknown: "Unbekannt",
  unknownCard: "Du hast diese Karte noch nicht gezogen.",
  questCompleted: "Quest abgeschlossen",
  notCompleted: "Noch nicht abgeschlossen",
  favorite: "Favorit",
  start: "Quest starten",
  repeat: "Quest wiederholen",
  repeated: "Quest wiederholt",
  coinsEarned: "Münzen erhalten",
  lastPlayed: "Zuletzt gespielt",
  longest: "Längste Session",
  personalBest: "Bestzeit",
  activeQuest: "Es läuft bereits eine Quest.",
  empty: "Keine Quests passen zu deinen Filtern.",
};
