export const englishGallery = {
  title: "Quest Gallery",
  navigation: "Quest gallery",
  close: "Close quest gallery",
  results: "{{count}} quests",
  results_one: "{{count}} quest",
  results_other: "{{count}} quests",
  clearSearch: "Clear search",
  overview: "Back to overview",
  excludeQuest: "Ban quest",
  excludeTooltip: "Removes this quest from your quest pool.",
  allowQuest: "Allow this quest again",
  excludedQuest: "Excluded from your quest pool",
  excludeTitle: "Don’t like this quest?",
  excludeDescription: "Banning “{{quest}}” removes it from future offers until you allow it again in the quest gallery.",
  keepQuestAndDontAskAgain: "Keep this quest and don’t ask again",
  keepQuest: "Keep in quest pool",
  closeExclude: "Close quest exclusion dialog",
  search: "Search quests…",
  filter: "Filter quests",
  filters: "Filters",
  filtersTitle: "Quest filters",
  filtersDescription:
    "Choose several values inside a group. Quests match across all selected groups.",
  applyFilters: "Apply filters",
  clearFilters: "Reset filters",
  statusFilter: "Progress",
  moodFilter: "Mood",
  genreFilter: "Genre",
  connectionModeFilter: "Connection",
  playStyleFilter: "Play style",
  typeFilter: "Quest type",
  rarityFilter: "Rarity",
  standard: "Default",
  special: "Special",
  gameFilter: "Game",
  anyGameFilter: "Any game",
  tagFilter: "Tags",
  all: "All",
  found: "Found quests",
  favorites: "Your favorites",
  completed: "Completed",
  uncompleted: "Uncompleted",
  banned: "Banned quests",
  browse: "Scroll or drag to browse quests",
  details: "Quest details and lifetime statistics",
  unknown: "Unknown",
  unknownCard: "You haven't drawn this card yet.",
  questCompleted: "Quest completed",
  notCompleted: "Quest not completed yet",
  unfinishedDescription: "You have not completed this quest yet.",
  favorite: "Favorite",
  start: "Start quest",
  repeat: "Repeat quest",
  repeated: "Quest repeated",
  coinsEarned: "Coins earned",
  lastPlayed: "Last played",
  longest: "Longest session",
  personalBest: "Personal best",
  activeQuest: "Finish or cancel your current quest before starting another.",
  empty: "No quests match your filters.",
};
export const germanGallery: Record<keyof typeof englishGallery, string> = {
  title: "Quests-Galerie",
  navigation: "Quests-Galerie",
  close: "Quests-Galerie schließen",
  results: "{{count}} Quests",
  results_one: "{{count}} Quest",
  results_other: "{{count}} Quests",
  clearSearch: "Suche leeren",
  overview: "Zurück zur Übersicht",
  excludeQuest: "Quest verbannen",
  excludeTooltip: "Entfernt diese Quest aus deinem Quest-Pool.",
  allowQuest: "Diese Quest wieder zulassen",
  excludedQuest: "Aus deinem Quest-Pool ausgeschlossen",
  excludeTitle: "Gefällt dir diese Quest nicht?",
  excludeDescription: "Wenn du „{{quest}}“ verbannst, wird sie aus deinem Quest-Pool entfernt, bis du sie in der Quests-Galerie wieder zulässt.",
  keepQuestAndDontAskAgain: "Quest behalten und nicht mehr fragen",
  keepQuest: "Im Quest-Pool behalten",
  closeExclude: "Dialog zum Ausschließen schließen",
  search: "Quests durchsuchen…",
  filter: "Quests filtern",
  filters: "Filter",
  filtersTitle: "Quest-Filter",
  filtersDescription:
    "Wähle mehrere Werte innerhalb einer Gruppe. Eine Quest muss zu allen gewählten Gruppen passen.",
  applyFilters: "Filter anwenden",
  clearFilters: "Filter zurücksetzen",
  statusFilter: "Fortschritt",
  moodFilter: "Stimmung",
  genreFilter: "Genre",
  connectionModeFilter: "Verbindung",
  playStyleFilter: "Spielweise",
  typeFilter: "Quest-Typ",
  rarityFilter: "Seltenheit",
  standard: "Standard",
  special: "Besonders",
  gameFilter: "Spiel",
  anyGameFilter: "Beliebiges Spiel",
  tagFilter: "Tags",
  all: "Alle Quests",
  found: "Gefundene Quests",
  favorites: "Deine Favoriten",
  completed: "Abgeschlossen",
  uncompleted: "Noch offen",
  banned: "Verbannte Quests",
  browse: "Scrollen oder ziehen, um Quests anzusehen",
  details: "Quest-Details und gesamte Statistik",
  unknown: "Unbekannt",
  unknownCard: "Du hast diese Karte noch nicht gezogen.",
  questCompleted: "Quest abgeschlossen",
  notCompleted: "Quest noch nicht abgeschlossen",
  unfinishedDescription: "Du hast diese Quest noch nicht abgeschlossen.",
  favorite: "Favorit",
  start: "Quest starten",
  repeat: "Quest wiederholen",
  repeated: "Quest wiederholt",
  coinsEarned: "Münzen erhalten",
  lastPlayed: "Zuletzt gespielt",
  longest: "Längste Session",
  personalBest: "Bestzeit",
  activeQuest: "Es läuft bereits eine Quest.",
  empty: "Keine Quests passen zu deinen Filtern.",
};
