export const englishLibrary = {
  setupEyebrow: "Your game shelf",
  setupTitle: "Welcome to sidesidequest",
  setupDescription: "Start with a curated games collection or make your own.",
  curatedHeading: "Starter collection",
  curatedDescription: "8 games and series, with quests made for them.",
  customHeading: "Your games",
  customDescription:
    "Add a game or a whole series and choose the activies you can do in-game.",
  addGame: "Add game",
  saveGame: "Save game",
  cancel: "Cancel",
  edit: "Edit",
  remove: "Remove",
  untitledGame: "XY",
  gameName: "Game or series name",
  gameNamePlaceholder: "Game name",
  gameIcon: "Icon",
  gameColor: "Color",
  iconChoice: "Use the {{icon}} icon",
  colorChoice: "Use the {{color}} color",
  capabilities: "What can you do in-game?",
  capabilitiesHint:
    "Choose the features available your game, each adds matching quests. A small set of flexible quests is always included.",
  reviewQuests: "Review quests",
  reviewQuestsHint:
    "Turn off any quest that does not fit. You can also browse all flexible quests and only add individual ones.",
  questCount_one: "{{count}} quest",
  questCount_other: "{{count}} quests",
  capabilityCount_one: "{{count}} feature",
  capabilityCount_other: "{{count}} features",
  noCustomGames: "Missing your game? Add it here, or use the collection above.",
  setupSelection_one: "{{count}} game selected",
  setupSelection_other: "{{count}} games selected",
  startSidequests: "Start sidequests",
  drawerTitle: "Game library",
  drawerDescription: "Your games, series, and the quests that fit them.",
  profileSummary: "Choose and configure your games",
  icons: {
    action: "action",
    adventure: "adventure",
    arcade: "arcade",
    building: "building",
    cards: "cards",
    cozy: "cozy",
    exploration: "exploration",
    fighting: "fighting",
    horror: "horror",
    multiplayer: "multiplayer",
    platformer: "platformer",
    puzzle: "puzzle",
    racing: "racing",
    rhythm: "rhythm",
    rpg: "role-playing",
    shooter: "shooter",
    simulation: "simulation",
    sports: "sports",
    strategy: "strategy",
    survival: "survival",
    boss: "boss fights",
    stealth: "stealth",
    equipment: "equipment",
    crafting: "crafting",
    fishing: "fishing",
    cooking: "cooking",
    farming: "farming and care",
    customization: "outfits",
    photography: "photo mode",
    "local-co-op": "local co-op",
    collectibles: "collectibles",
    lore: "stories and lore",
  },
  capabilityLabels: {
    "open-world": "Explore an open world",
    "missions-or-levels": "Complete missions or levels",
    "rounds-or-matches": "Play rounds or matches",
    combat: "Fight enemies",
    "boss-fights": "Face boss fights",
    stealth: "Sneak past enemies",
    "equipment-loadouts": "Change equipment or loadouts",
    puzzles: "Solve puzzles",
    building: "Build or place structures",
    crafting: "Craft items",
    fishing: "Catch fish",
    cooking: "Prepare meals",
    "farming-or-care": "Tend plants, animals, or characters",
    "driving-or-racing": "Drive vehicles or race",
    "advanced-traversal": "Climb, glide, or perform movement tricks",
    customization: "Change appearances or outfits",
    "photo-mode": "Take pictures in photo mode",
    "online-teamplay": "Play together online",
    "local-multiplayer": "Play together on one device",
    collectibles: "Find collectibles",
    "choices-or-lore": "Read lore or follow dialogue",
  },
  personalTitle: "Your own library",
  personalDescription:
    "Add the games you play. You can change this later from your profile.",
  devStartDescription:
    "{{count}} games and series. Jump straight to your mood.",
  personalStartDescription:
    "Pick from the collection or add any game you like.",
  continueWithoutGames: "Start with any-game quests",
  backToStart: "Back",
  backToLibrary: "Back to library",
  collectionHint: "A selection of games and series with dedicated quests.",
  addAll: "Add all",
  removeAll: "Remove all",
  searchGames: "Find a game or series",
  game: "Game",
  series: "Series",
  noSearchResults: "No match in the collection. Add your game below.",
  editGame: "Edit {{game}}",
  removeGame: "Remove {{game}}",
  confirmRemove: "Remove?",
  appearance: "Icon",
  reviewSelection: "Your quest selection",
  searchQuests: "Find a quest",
  showMatched: "Show matched quests",
  showAllReusable: "Browse all reusable quests",
  resetMatches: "Reset to feature matches",
  noQuestResults: "No quests match this search.",
  colorNames: {
    relax: "Mint",
    explore: "Amber",
    progress: "Blue",
    create: "Pink",
    challenge: "Coral",
    connect: "Lime",
    nostalgic: "Lilac",
    overwhelmed: "Peach",
    restless: "Yellow",
    focused: "Indigo",
    curious: "Turquoise",
    "low-energy": "Slate",
  },
};

export const germanLibrary = {
  setupEyebrow: "Dein Spieleregal",
  setupTitle: "Willkommen auf sidesidequest",
  setupDescription:
    "Starte mit einer ausgewählten Spielesammlung oder erstelle deine eigene.",
  curatedHeading: "Starter collection",
  curatedDescription: "8 Spiele und Reihen mit eigenen Quests.",
  customHeading: "Deine Spiele",
  customDescription:
    "Füge ein Spiel oder eine ganze Reihe hinzu und wähle die Aktivitäten, die im Spiel möglich sind.",
  addGame: "Spiel hinzufügen",
  saveGame: "Spiel speichern",
  cancel: "Abbrechen",
  edit: "Bearbeiten",
  remove: "Entfernen",
  untitledGame: "XY",
  gameName: "Name des Spiels oder der Reihe",
  gameNamePlaceholder: "Game name",
  gameIcon: "Icon",
  gameColor: "Farbe",
  iconChoice: "Icon {{icon}} verwenden",
  colorChoice: "Farbe {{color}} verwenden",
  capabilities: "Was kann man im Spiel machen?",
  capabilitiesHint:
    "Wähle die Features deines Spiels, womit passende Quests hinzugefügt werden. Einige flexible Quests sind immer dabei.",
  reviewQuests: "Quests ansehen",
  reviewQuestsHint:
    "Entferne unpassende Quests für dieses Spiel. Du kannst auch alle flexiblen Quests durchsuchen und nur einzelne hinzufügen.",
  questCount_one: "{{count}} Quest",
  questCount_other: "{{count}} Quests",
  capabilityCount_one: "{{count}} Feature",
  capabilityCount_other: "{{count}} Features",
  noCustomGames:
    "Dein Spiel fehlt? Füge es hier hinzu oder nutze die Sammlung oben.",
  setupSelection_one: "{{count}} Spiel ausgewählt",
  setupSelection_other: "{{count}} Spiele ausgewählt",
  startSidequests: "Sidequests starten",
  drawerTitle: "Spielebibliothek",
  drawerDescription: "Deine Spiele, Reihen und die passenden Quests.",
  profileSummary: "Spiele auswählen und einrichten",
  icons: {
    action: "Action",
    adventure: "Abenteuer",
    arcade: "Arcade",
    building: "Bauen",
    cards: "Karten",
    cozy: "Gemütlich",
    exploration: "Erkundung",
    fighting: "Kampfspiel",
    horror: "Horror",
    multiplayer: "Multiplayer",
    platformer: "Platformer",
    puzzle: "Rätsel",
    racing: "Rennspiel",
    rhythm: "Rhythmus",
    rpg: "Rollenspiel",
    shooter: "Shooter",
    simulation: "Simulation",
    sports: "Sport",
    strategy: "Strategie",
    survival: "Survival",
    boss: "Bosskämpfe",
    stealth: "Schleichen",
    equipment: "Ausrüstung",
    crafting: "Herstellen",
    fishing: "Angeln",
    cooking: "Kochen",
    farming: "Pflanzen und Pflege",
    customization: "Outfits",
    photography: "Fotomodus",
    "local-co-op": "Lokaler Koop",
    collectibles: "Sammelobjekte",
    lore: "Geschichten und Spielwelt",
  },
  capabilityLabels: {
    "open-world": "Eine offene Welt erkunden",
    "missions-or-levels": "Missionen oder Level abschließen",
    "rounds-or-matches": "Runden oder Matches spielen",
    combat: "Gegen Gegner kämpfen",
    "boss-fights": "Bosskämpfe bestreiten",
    stealth: "An Gegnern vorbeischleichen",
    "equipment-loadouts": "Ausrüstung oder Loadouts wechseln",
    puzzles: "Rätsel lösen",
    building: "Bauen oder Objekte platzieren",
    crafting: "Gegenstände herstellen",
    fishing: "Fische fangen",
    cooking: "Mahlzeiten zubereiten",
    "farming-or-care": "Pflanzen, Tiere oder Figuren versorgen",
    "driving-or-racing": "Fahrzeuge steuern oder Rennen fahren",
    "advanced-traversal": "Klettern, gleiten oder Bewegungstricks nutzen",
    customization: "Aussehen oder Outfits ändern",
    "photo-mode": "Bilder im Fotomodus aufnehmen",
    "online-teamplay": "Online zusammen spielen",
    "local-multiplayer": "An einem Gerät zusammen spielen",
    collectibles: "Sammelobjekte finden",
    "choices-or-lore": "Hintergrundtexte lesen oder Dialogen folgen",
  },
  personalTitle: "Deine eigene Bibliothek",
  personalDescription:
    "Füge die Spiele hinzu, die du spielst. Du kannst das später im Profil ändern.",
  devStartDescription:
    "{{count}} Spiele und Reihen. Direkt zur Stimmungsauswahl.",
  personalStartDescription:
    "Wähle aus der Sammlung oder füge ein beliebiges Spiel hinzu.",
  continueWithoutGames: "Mit Quests für beliebige Spiele starten",
  backToStart: "Zurück",
  backToLibrary: "Zur Bibliothek",
  collectionHint: "Eine Auswahl von Spielen und Reihen mit eigenen Quests",
  addAll: "Alle hinzufügen",
  removeAll: "Alle entfernen",
  searchGames: "Spiel oder Reihe suchen",
  game: "Spiel",
  series: "Reihe",
  noSearchResults: "Kein Treffer in der Sammlung. Füge dein Spiel unten hinzu.",
  editGame: "{{game}} bearbeiten",
  removeGame: "{{game}} entfernen",
  confirmRemove: "Entfernen?",
  appearance: "Icon",
  reviewSelection: "Deine Quest-Auswahl",
  searchQuests: "Quest suchen",
  showMatched: "Passende Quests zeigen",
  showAllReusable: "Alle wiederverwendbaren Quests",
  resetMatches: "Nach Features zurücksetzen",
  noQuestResults: "Keine Quests für diese Suche.",
  colorNames: {
    relax: "Mint",
    explore: "Bernstein",
    progress: "Blau",
    create: "Pink",
    challenge: "Koralle",
    connect: "Limette",
    nostalgic: "Flieder",
    overwhelmed: "Pfirsich",
    restless: "Gelb",
    focused: "Indigo",
    curious: "Türkis",
    "low-energy": "Schiefer",
  },
};
