export const englishLibrary = {
  automaticMatches: "Automatic matches",
  manualApprovals: "Manually approved",
  otherQuests: "Other quests",
  matchedActivities: "Selected activities: {{activities}}",
  missingActivities: "Still needs: {{activities}}",
  missingGenre: "Choose a genre: {{genres}}",
  manuallyExcluded: "Manually excluded",
  manualOnlyHint: "Check that the game supports this quest before approving it manually.",
  requirementAnd: " and ",
  requirementOr: " or ",
  activityMatchCount_one: "{{count}} linked quest",
  activityMatchCount_other: "{{count}} linked quests",
  genres: "Genres",
  genresHint:
    "Choose several genres if they fit. They suggest activities and refine genre-specific quests. Activities still decide which systems a quest can use.",
  activitySuggestionsHint:
    "Activities unlock matching quests. Some quests need several activities or a specific genre.",
  suggestedActivity: "Suggested",
  welcome: "Welcome to",
  welcomeDescription:
    "A little starter help for everyone with too many video games.",
  moreInformation: "More information",
  changeLanguage: "Change language",
  changeTheme: "Change theme",
  changeThemeTo: "Change theme to {{theme}}",
  closeInformation: "Close information",
  createLibrary: "Create your own library",
  startWithoutSetup: "Start without setup",
  overviewIntro: "Choose games from Eddie’s Collection or add your own",
  finishSetup: "Finish setup",
  optional: "Optional",
  configureGame: "Game & quest options",
  editorIntro:
    "Give your game a name and look, then choose what you can do in it",
  activitiesIntro: "Choose everything you can do in",
  possibleActivities: "Genres & activities",
  adjust: "Adjust",
  chooseActivities: "Choose genres and what you can do in this game.",
  addActivities: "Add activities",
  saveActivities: "Save",
  saveLibrary: "Save library",
  editGameTitle: "Edit game",
  selectActivities: "Describe your game",
  activitiesView: "Activities",
  questsView: "Quests",
  activityView: "View activities or quests",
  drawerActivitiesIntro: "Describe",
  drawerActivitiesOutro:
    " with genres and activities to find fitting sidequests.",
  selectedActivities: "{{count}} selected",
  selectedQuests: "{{count}} quests selected",
  searchActivities: "Search",
  back: "Back",
  done: "Done",
  previousIcons: "Previous icons",
  nextIcons: "Next icons",
  moreColors: "More colors",
  previousColors: "Previous colors",
  iconPage: "Icon page {{page}}",
  previewRelax: "Relax",
  previewNostalgia: "Nostalgia",
  scrollDown: "Scroll down",

  setupEyebrow: "Your game shelf",
  setupTitle: "Welcome to sidesidequest",
  setupDescription: "Choose from Eddie’s Collection or make your own.",
  curatedHeading: "Eddie’s Collection",
  supportedGames: "Supported games",
  noCuratedGames: "No games from Eddie’s Collection selected",
  selectGame: "Select game",
  saveSelection: "Save",
  curatedDescription: "Games and series with quests made for them.",
  questMode: "Quests for {{game}}",
  curatedOnly: "Curated only",
  curatedAndFlexible: "Curated + flexible",
  installments: "Which titles do you play?",
  chooseInstallment:
    "Pick at least one game in this series to get matching quests.",
  customHeading: "Your games",
  customDescription:
    "Add any game and choose the activities its quests can use.",
  addGame: "Add game",
  add: "Add",
  saveGame: "Save",
  cancel: "Cancel",
  edit: "Edit",
  remove: "Remove",
  untitledGame: "Your game",
  gameName: "Game or series name",
  gameNamePlaceholder: "Game name",
  gameIcon: "Icon",
  gameColor: "Color",
  iconChoice: "Use the {{icon}} icon",
  colorChoice: "Use the {{color}} color",
  capabilities: "What can you do in-game?",
  capabilitiesHint:
    "Genres describe the game; activities describe its playable systems. Review the matching quests before saving.",
  reviewQuests: "Review quests",
  reviewQuestsHint:
    "Turn off any quest that does not fit. You can also browse all flexible quests and only add individual ones.",
  questCount_one: "{{count}} quest",
  questCount_other: "{{count}} quests",
  capabilityCount_one: "{{count}} feature",
  capabilityCount_other: "{{count}} features",
  noCustomGames: "No personal games yet.",
  setupSelection_one: "{{count}} game selected",
  setupSelection_other: "{{count}} games selected",
  startSidequests: "Start sidequests",
  drawerTitle: "Game library",
  drawerDescription: "Your games, series, and the quests that fit them.",
  profileSummary: "Choose and configure your games",
  profileSummaryCounts: "{{curated}} curated / {{custom}} personal games",
  icons: {
    robot: "robot",
    dragon: "dragon",
    "magic-wand": "magic wand",
    mountain: "mountain",
    anchor: "anchor",
    paw: "paw",
    zombie: "Zombie",
    vampire: "Vampire",
    "slasher-mask": "Slasher mask",
    "haunted-house": "Haunted house",
    ghost: "Ghost",
    castle: "Castle",
    space: "Space",
    radiation: "Radiation",

    action: "action",
    adventure: "adventure",
    arcade: "arcade",
    building: "building",
    cards: "cards",
    cozy: "cozy",
    exploration: "exploration",
    fighting: "fighting",
    horror: "horror",
    multiplayer: "multiplayer",
    platformer: "platformer",
    puzzle: "puzzle",
    racing: "racing",
    rhythm: "rhythm",
    rpg: "role-playing",
    shooter: "shooter",
    simulation: "simulation",
    sports: "sports",
    strategy: "strategy",
    survival: "survival",
    boss: "boss fights",
    stealth: "stealth",
    equipment: "equipment",
    crafting: "crafting",
    fishing: "fishing",
    cooking: "cooking",
    farming: "farming and care",
    customization: "outfits",
    photography: "photo mode",
    "local-co-op": "local co-op",
    collectibles: "collectibles",
    lore: "stories and lore",
  },
  capabilityLabels: {
    platforming: "Jump through obstacle courses and platforming levels",
    "character-abilities":
      "Choose characters with different playable abilities",
    "tactical-gadgets": "Use gadgets to breach, block, or protect routes",
    "scouting-tools": "Scout with cameras, drones, or vision wards",
    "remote-scouting": "Control a camera or drone to scout rooms and routes",
    "lanes-and-towers": "Fight along minion lanes and attack towers",
    "time-trials": "Replay timed routes with recorded results",
    "rhythm-play": "Play songs with timed inputs and result screens",
    "card-decks": "Edit a deck and play card battles",
    "card-mulligan": "Replace opening cards with a mulligan",
    "unit-command": "Command several units in tactical battles",
    automation: "Connect machines into automated production lines",

    "open-world": "Explore a world freely",
    "missions-or-levels": "Play missions or levels with objectives",
    "rounds-or-matches": "Play short, standalone rounds",
    "whole-matches": "Play full matches, including all their rounds",
    "combat-loadouts": "Choose weapons for combat encounters",
    "weapon-pickups": "Pick up and use weapons found during play",
    "equipment-upgrades": "Upgrade owned equipment and use its changed effects",
    "bot-modes": "Play solo against computer-controlled opponents",
    "replayable-tutorials": "Replay guided tutorials to refresh the controls",
    "combat-spells": "Deal damage with spells",
    "space-exploration": "Land on and explore planets",
    "free-space-flight": "Fly freely through space",
    "dynamic-weather": "Explore while the weather changes",
    swimming: "Swimming",
    diving: "Underwater exploration",
    "moving-patrols": "Moving patrols",
    "stealth-takedowns": "Stealth takedowns",
    "theft-or-loot": "Stealing or looting",
    "placeable-gadgets": "Placeable gadgets",
    "replayable-encounters": "Replayable encounters",
    decoration: "Decoration",
    "level-editors": "Level editors",
    "inventory-storage": "Inventory storage",
    "material-gathering": "Gather resources",
    "practice-ranges": "Practice ranges with fixed targets",
    "boss-fights": "Retry boss fights",
    stealth: "Sneak past patrolling guards",
    puzzles: "Solve self-contained puzzles",
    building: "Build structures from placed pieces",
    crafting: "Make items from crafting recipes",
    fishing: "Catch fish with a rod",
    cooking: "Prepare dishes from recipes",
    "grow-crops": "Plant, harvest, and replant crops",
    "animal-care": "Keep and feed animals",
    "free-driving": "Drive freely outside races",
    racing: "Race on tracks against other vehicles",
    "advanced-traversal": "Climb, jump, or use movement abilities",
    customization: "Create looks with owned cosmetics",
    "photo-mode": "Frame and save photos in photo mode",
    "online-teamplay": "Work on shared objectives online",
    "local-multiplayer": "Take short turns on the same device",
    collectibles: "Find items tracked in a collection",
    "choices-or-lore": "Read story entries or optional dialogue",
    "optional-dialogue": "Talk to characters through optional conversations",
    "readable-journal": "Read unlocked journal, lore, or codex entries",
    trading: "Sell inventory items to merchants",
    hunting: "Hunt animals for materials",
    "animal-companions": "Command animal companions in combat",
    "skate-tricks": "Land grinds and flip tricks",
    "sports-goals": "Score goals against computer opponents",
    "extraction-runs": "Loot containers and extract in solo runs",
  },
  personalTitle: "Your own library",
  personalDescription:
    "Add the games you play. You can change this later from your profile.",
  devStartDescription:
    "{{count}} games and series. Jump straight to your mood.",
  personalStartDescription:
    "Pick from the collection or add any game you like.",
  continueWithoutGames: "Start with any-game quests",
  backToStart: "Back",
  backToLibrary: "Back to library",
  collectionHint:
    "Games and series from Eddie’s own collection, with quests made for them.",
  addAll: "Add all",
  removeAll: "Remove all",
  searchGames: "Find a game or series",
  game: "Game",
  series: "Series",
  noSearchResults: "No match in the collection. Add your game below.",
  editGame: "Edit {{game}}",
  removeGame: "Remove {{game}}",
  confirmRemove: "Remove?",
  appearance: "Icon",
  reviewSelection: "Your quest selection",
  searchQuests: "Find a quest",
  showMatched: "Show matched quests",
  showAllReusable: "Browse all reusable quests",
  resetMatches: "Reset to genre & activity matches",
  noActivityResults: "No activities match this search.",
  noQuestResults: "No quests match this search.",
  colorNames: {
    violet: "Violet",
    teal: "Teal",
    rose: "Rose",
    orange: "Orange",
    relax: "Mint",
    explore: "Amber",
    progress: "Blue",
    create: "Pink",
    challenge: "Coral",
    connect: "Lime",
    nostalgic: "Lilac",
    overwhelmed: "Peach",
    restless: "Yellow",
    focused: "Indigo",
    curious: "Turquoise",
    "low-energy": "Slate",
  },
};

export const germanLibrary = {
  automaticMatches: "Automatisch passend",
  manualApprovals: "Manuell bestätigt",
  otherQuests: "Weitere Quests",
  matchedActivities: "Gewählte Aktivitäten: {{activities}}",
  missingActivities: "Fehlt noch: {{activities}}",
  missingGenre: "Wähle ein Genre: {{genres}}",
  manuallyExcluded: "Manuell ausgeschlossen",
  manualOnlyHint: "Prüfe, ob das Spiel diese Quest unterstützt, bevor du sie manuell bestätigst.",
  requirementAnd: " und ",
  requirementOr: " oder ",
  activityMatchCount_one: "{{count}} verknüpfte Quest",
  activityMatchCount_other: "{{count}} verknüpfte Quests",
  genres: "Genres",
  genresHint: "Genres grenzen die Quests ein.",
  activitySuggestionsHint:
    "Aktivitäten schalten passende Quests frei. Manche Quests brauchen mehrere Aktivitäten oder ein bestimmtes Genre.",
  suggestedActivity: "Vorgeschlagen",
  welcome: "Willkommen bei",
  welcomeDescription:
    "Eine kleine Starthilfe für alle mit zu vielen Videospielen.",
  moreInformation: "Mehr Informationen",
  changeLanguage: "Sprache ändern",
  changeTheme: "Theme ändern",
  changeThemeTo: "Theme zu {{theme}} ändern",
  closeInformation: "Informationen schließen",
  createLibrary: "Eigene Bibliothek erstellen",
  startWithoutSetup: "Ohne Einrichtung starten",
  overviewIntro: "Wähle Spiele aus Eddies Sammlung oder füge eigene hinzu",
  finishSetup: "Einrichtung abschließen",
  optional: "Optional",
  configureGame: "Spiel- & Quest-Optionen",
  editorIntro:
    "Gib deinem Spiel einen Namen und Look und wähle dann seine Aktivitäten",
  activitiesIntro: "Wähle alles aus, was man in",
  possibleActivities: "Genres & Aktivitäten",
  adjust: "Anpassen",
  chooseActivities: "Wähle Genres und was du im Spiel machen kannst.",
  addActivities: "Aktivitäten hinzufügen",
  saveActivities: "Speichern",
  saveLibrary: "Bibliothek speichern",
  editGameTitle: "Spiel bearbeiten",
  selectActivities: "Spiel beschreiben",
  activitiesView: "Aktivitäten",
  questsView: "Quests",
  activityView: "Aktivitäten oder Quests anzeigen",
  drawerActivitiesIntro: "Beschreibe",
  drawerActivitiesOutro:
    " mit Genres und Aktivitäten, um passende sidequests zu finden.",
  selectedActivities: "{{count}} ausgewählt",
  selectedQuests: "{{count}} Quests ausgewählt",
  searchActivities: "Suche",
  back: "Zurück",
  done: "Fertig",
  previousIcons: "Vorherige Icons",
  nextIcons: "Nächste Icons",
  moreColors: "Weitere Farben",
  previousColors: "Vorherige Farben",
  iconPage: "Icon-Seite {{page}}",
  previewRelax: "Entspannt",
  previewNostalgia: "Nostalgie",
  scrollDown: "Weiter nach unten",

  setupEyebrow: "Dein Spieleregal",
  setupTitle: "Willkommen auf sidesidequest",
  setupDescription: "Wähle aus Eddies Sammlung oder erstelle deine eigene.",
  curatedHeading: "Eddies Sammlung",
  supportedGames: "Unterstützte Spiele",
  noCuratedGames: "Keine Spiele aus Eddies Sammlung ausgewählt",
  selectGame: "Spiel auswählen",
  saveSelection: "Speichern",
  curatedDescription: "Spiele und Reihen mit eigenen Quests.",
  questMode: "Quests für {{game}}",
  curatedOnly: "Nur kuratierte",
  curatedAndFlexible: "Kuratierte + flexible",
  installments: "Welche Teile spielst du?",
  chooseInstallment:
    "Wähle mindestens einen Teil, um passende Quests zu bekommen.",
  customHeading: "Deine Spiele",
  customDescription:
    "Füge ein beliebiges Spiel hinzu und wähle die Aktivitäten für seine Quests.",
  addGame: "Spiel hinzufügen",
  add: "Hinzufügen",
  saveGame: "Speichern",
  cancel: "Abbrechen",
  edit: "Bearbeiten",
  remove: "Entfernen",
  untitledGame: "Dein Spiel",
  gameName: "Name des Spiels oder der Reihe",
  gameNamePlaceholder: "Spielname",
  gameIcon: "Icon",
  gameColor: "Farbe",
  iconChoice: "Icon {{icon}} verwenden",
  colorChoice: "Farbe {{color}} verwenden",
  capabilities: "Was kann man im Spiel machen?",
  capabilitiesHint: "Damit werden passende Quests für dieses Spiel verknüpft",
  reviewQuests: "Quests ansehen",
  reviewQuestsHint:
    "Entferne unpassende Quests für dieses Spiel. Du kannst auch alle flexiblen Quests durchsuchen und nur einzelne hinzufügen.",
  questCount_one: "{{count}} Quest",
  questCount_other: "{{count}} Quests",
  capabilityCount_one: "{{count}} Feature",
  capabilityCount_other: "{{count}} Features",
  noCustomGames: "Noch keine eigenen Spiele.",
  setupSelection_one: "{{count}} Spiel ausgewählt",
  setupSelection_other: "{{count}} Spiele ausgewählt",
  startSidequests: "Sidequests starten",
  drawerTitle: "Spielebibliothek",
  drawerDescription: "Deine Spiele, Reihen und die passenden Quests.",
  profileSummaryCounts: "{{curated}} kuratierte / {{custom}} eigene Spiele",
  profileSummary: "Spiele auswählen und einrichten",
  icons: {
    robot: "Roboter",
    dragon: "Drache",
    "magic-wand": "Zauberstab",
    mountain: "Berg",
    anchor: "Anker",
    paw: "Pfote",
    zombie: "Zombie",
    vampire: "Vampir",
    "slasher-mask": "Horrormaske",
    "haunted-house": "Spukhaus",
    ghost: "Geist",
    castle: "Burg",
    space: "Weltraum",
    radiation: "Radioaktivität",

    action: "Action",
    adventure: "Abenteuer",
    arcade: "Arcade",
    building: "Bauen",
    cards: "Karten",
    cozy: "Gemütlich",
    exploration: "Erkundung",
    fighting: "Kampfspiel",
    horror: "Horror",
    multiplayer: "Multiplayer",
    platformer: "Platformer",
    puzzle: "Rätsel",
    racing: "Rennspiel",
    rhythm: "Rhythmus",
    rpg: "Rollenspiel",
    shooter: "Shooter",
    simulation: "Simulation",
    sports: "Sport",
    strategy: "Strategie",
    survival: "Survival",
    boss: "Bosskämpfe",
    stealth: "Schleichen",
    equipment: "Ausrüstung",
    crafting: "Herstellen",
    fishing: "Angeln",
    cooking: "Kochen",
    farming: "Pflanzen und Pflege",
    customization: "Outfits",
    photography: "Fotomodus",
    "local-co-op": "Lokaler Koop",
    collectibles: "Sammelobjekte",
    lore: "Geschichten und Spielwelt",
  },
  capabilityLabels: {
    platforming: "Sprungpassagen und Plattform-Level spielen",
    "character-abilities":
      "Figuren mit unterschiedlichen Fähigkeiten auswählen",
    "tactical-gadgets": "Mit Gadgets Wege öffnen, sperren oder schützen",
    "scouting-tools": "Mit Kameras, Drohnen oder Wards aufklären",
    "remote-scouting": "Mit einer steuerbaren Kamera oder Drohne Räume und Wege auskundschaften",
    "lanes-and-towers": "Auf Minion-Lanes kämpfen und Türme angreifen",
    "time-trials": "Zeitrennen mit erfassten Ergebnissen wiederholen",
    "rhythm-play": "Songs mit getimten Eingaben und Ergebnisanzeige spielen",
    "card-decks": "Ein Deck bearbeiten und Kartenkämpfe spielen",
    "card-mulligan": "Mit einem Mulligan Karten der Starthand austauschen",
    "unit-command": "Mehrere Einheiten in taktischen Kämpfen befehligen",
    automation: "Maschinen zu automatischen Produktionsketten verbinden",

    "open-world": "Eine Welt frei erkunden",
    "missions-or-levels": "Missionen oder Level mit Zielen spielen",
    "rounds-or-matches": "Kurze, eigenständige Runden spielen",
    "whole-matches": "Ganze Matches mit allen zugehörigen Runden spielen",
    "combat-loadouts": "Waffen für Kämpfe auswählen",
    "weapon-pickups": "Unterwegs gefundene Waffen aufheben und benutzen",
    "equipment-upgrades": "Eigene Ausrüstung upgraden und ihre neue Wirkung nutzen",
    "bot-modes": "Solo gegen Bots oder CPU-Gegner spielen",
    "replayable-tutorials": "Geführte Tutorials zum Auffrischen der Steuerung wiederholen",
    "combat-spells": "Mit Zaubern Schaden verursachen",
    "space-exploration": "Auf Planeten landen und sie erkunden",
    "free-space-flight": "Frei durchs All fliegen",
    "dynamic-weather": "Bei wechselndem Wetter erkunden",
    swimming: "Schwimmen",
    diving: "Unterwasser erkunden",
    "moving-patrols": "Bewegliche Patrouillen",
    "stealth-takedowns": "Lautlos ausschalten",
    "theft-or-loot": "Stehlen oder plündern",
    "placeable-gadgets": "Platzierbare Gadgets",
    "replayable-encounters": "Wiederholbare Begegnungen",
    decoration: "Einrichten",
    "level-editors": "Leveleditoren",
    "inventory-storage": "Inventarlager",
    "material-gathering": "Rohstoffe sammeln",
    "practice-ranges": "Übungsplätze mit festen Zielen",
    "boss-fights": "Bosskämpfe erneut versuchen",
    stealth: "An patrouillierenden Wachen vorbeischleichen",
    puzzles: "Einzelne Rätsel lösen",
    building: "Gebäude aus Bauteilen errichten",
    crafting: "Gegenstände nach Rezepten herstellen",
    fishing: "Fische mit einer Angel fangen",
    cooking: "Gerichte nach Rezepten zubereiten",
    "grow-crops": "Nutzpflanzen säen, ernten und neu pflanzen",
    "animal-care": "Tiere halten und füttern",
    "free-driving": "Abseits von Rennen frei fahren",
    racing: "Auf Strecken gegen andere Fahrzeuge fahren",
    "advanced-traversal": "Klettern, springen oder Bewegungsfähigkeiten nutzen",
    customization: "Looks mit vorhandenen Kosmetikobjekten gestalten",
    "photo-mode": "Bilder im Fotomodus gestalten und speichern",
    "online-teamplay": "Online an gemeinsamen Zielen arbeiten",
    "local-multiplayer": "Kurze Züge am selben Gerät abwechseln",
    collectibles: "Erfasste Sammelobjekte finden",
    "choices-or-lore": "Storyeinträge oder optionale Dialoge lesen",
    "optional-dialogue": "Optionale Gespräche mit Figuren führen",
    "readable-journal": "Freigeschaltete Journal-, Lore- oder Kodexeinträge lesen",
    trading: "Inventargegenstände an Händler verkaufen",
    hunting: "Tiere für Materialien jagen",
    "animal-companions": "Tierbegleitern im Kampf Befehle geben",
    "skate-tricks": "Grinds und Flip-Tricks landen",
    "sports-goals": "Tore gegen Computergegner erzielen",
    "extraction-runs": "Behälter plündern und solo extrahieren",
  },
  personalTitle: "Deine eigene Bibliothek",
  personalDescription:
    "Füge die Spiele hinzu, die du spielst. Du kannst das später im Profil ändern.",
  devStartDescription:
    "{{count}} Spiele und Reihen. Direkt zur Stimmungsauswahl.",
  personalStartDescription:
    "Wähle aus der Sammlung oder füge ein beliebiges Spiel hinzu.",
  continueWithoutGames: "Mit Quests für beliebige Spiele starten",
  backToStart: "Zurück",
  backToLibrary: "Zur Bibliothek",
  collectionHint:
    "Spiele und Reihen aus Eddies eigener Sammlung, mit eigenen Quests",
  addAll: "Alle hinzufügen",
  removeAll: "Alle entfernen",
  searchGames: "Spiel oder Reihe suchen",
  game: "Spiel",
  series: "Reihe",
  noSearchResults: "Kein Treffer in der Sammlung. Füge dein Spiel unten hinzu.",
  editGame: "{{game}} bearbeiten",
  removeGame: "{{game}} entfernen",
  confirmRemove: "Entfernen?",
  appearance: "Icon",
  reviewSelection: "Deine Quest-Auswahl",
  searchQuests: "Quest suchen",
  showMatched: "Passende Quests zeigen",
  showAllReusable: "Alle wiederverwendbaren Quests",
  resetMatches: "Nach Genres & Aktivitäten zurücksetzen",
  noActivityResults: "Keine Aktivitäten für diese Suche.",
  noQuestResults: "Keine Quests für diese Suche.",
  colorNames: {
    violet: "Violett",
    teal: "Petrol",
    rose: "Rosenrot",
    orange: "Orange",
    relax: "Mint",
    explore: "Bernstein",
    progress: "Blau",
    create: "Pink",
    challenge: "Koralle",
    connect: "Limette",
    nostalgic: "Flieder",
    overwhelmed: "Pfirsich",
    restless: "Gelb",
    focused: "Indigo",
    curious: "Türkis",
    "low-energy": "Schiefer",
  },
};
