export const englishLibrary = {
  welcome: "Welcome to",
  welcomeDescription:
    "A little starter help for everyone with too many video games.",
  moreInformation: "More information",
  changeLanguage: "Change language",
  changeTheme: "Change theme",
  changeThemeTo: "Change theme to {{theme}}",
  closeInformation: "Close information",
  createLibrary: "Create your own library",
  startWithoutSetup: "Start without setup",
  overviewIntro: "Choose games from the starter collection or add your own",
  finishSetup: "Finish setup",
  optional: "Optional",
  configureGame: "Game & quest options",
  editorIntro:
    "Give your game a name and look, then choose what you can do in it",
  activitiesIntro: "Choose everything you can do in",
  possibleActivities: "Possible activities",
  adjust: "Adjust",
  chooseActivities: "Choose what you can do in this game.",
  addActivities: "Add activities",
  saveActivities: "Save activities",
  saveLibrary: "Save library",
  editGameTitle: "Edit game",
  selectActivities: "Select activities",
  activitiesView: "Activities",
  questsView: "Quests",
  activityView: "View activities or quests",
  drawerActivitiesIntro: "Choose everything you can do in",
  drawerActivitiesOutro: ". These will become your personal sidequests.",
  selectedActivities: "{{count}} selected",
  selectedQuests: "{{count}} quests selected",
  searchActivities: "Search",
  back: "Back",
  done: "Done",
  previousIcons: "Previous icons",
  nextIcons: "Next icons",
  moreColors: "More colors",
  previousColors: "Previous colors",
  iconPage: "Icon page {{page}}",
  previewRelax: "Relax",
  previewNostalgia: "Nostalgia",
  scrollDown: "Scroll down",

  setupEyebrow: "Your game shelf",
  setupTitle: "Welcome to sidesidequest",
  setupDescription: "Start with a curated games collection or make your own.",
  curatedHeading: "Starter collection",
  supportedGames: "Supported games",
  noCuratedGames: "No starter games selected",
  selectGame: "Select game",
  saveSelection: "Save",
  curatedDescription: "Games and series with quests made for them.",
  questMode: "Quests for {{game}}",
  curatedOnly: "Curated only",
  curatedAndFlexible: "Curated + flexible",
  installments: "Supported titles",
  chooseInstallment:
    "Pick at least one game in this series to get matching quests.",
  customHeading: "Your games",
  customDescription:
    "Add any game and choose the activities its quests can use.",
  addGame: "Add game",
  add: "Add",
  saveGame: "Save game",
  cancel: "Cancel",
  edit: "Edit",
  remove: "Remove",
  untitledGame: "Your game",
  gameName: "Game or series name",
  gameNamePlaceholder: "Game name",
  gameIcon: "Icon",
  gameColor: "Color",
  iconChoice: "Use the {{icon}} icon",
  colorChoice: "Use the {{color}} color",
  capabilities: "What can you do in-game?",
  capabilitiesHint:
    "Activities find flexible quests that work with this game. You can review every match before saving.",
  reviewQuests: "Review quests",
  reviewQuestsHint:
    "Turn off any quest that does not fit. You can also browse all flexible quests and only add individual ones.",
  questCount_one: "{{count}} quest",
  questCount_other: "{{count}} quests",
  capabilityCount_one: "{{count}} feature",
  capabilityCount_other: "{{count}} features",
  noCustomGames: "No personal games yet.",
  setupSelection_one: "{{count}} game selected",
  setupSelection_other: "{{count}} games selected",
  startSidequests: "Start sidequests",
  drawerTitle: "Game library",
  drawerDescription: "Your games, series, and the quests that fit them.",
  profileSummary: "Choose and configure your games",
  profileSummaryCounts: "{{curated}} curated / {{custom}} personal games",
  icons: {
    zombie: "Zombie",
    vampire: "Vampire",
    "slasher-mask": "Slasher mask",
    "haunted-house": "Haunted house",
    ghost: "Ghost",
    castle: "Castle",
    space: "Space",
    radiation: "Radiation",

    action: "action",
    adventure: "adventure",
    arcade: "arcade",
    building: "building",
    cards: "cards",
    cozy: "cozy",
    exploration: "exploration",
    fighting: "fighting",
    horror: "horror",
    multiplayer: "multiplayer",
    platformer: "platformer",
    puzzle: "puzzle",
    racing: "racing",
    rhythm: "rhythm",
    rpg: "role-playing",
    shooter: "shooter",
    simulation: "simulation",
    sports: "sports",
    strategy: "strategy",
    survival: "survival",
    boss: "boss fights",
    stealth: "stealth",
    equipment: "equipment",
    crafting: "crafting",
    fishing: "fishing",
    cooking: "cooking",
    farming: "farming and care",
    customization: "outfits",
    photography: "photo mode",
    "local-co-op": "local co-op",
    collectibles: "collectibles",
    lore: "stories and lore",
  },
  capabilityLabels: {
    magic: "Cast spells in combat",
    trading: "Buy and sell items",
    hunting: "Hunt animals for materials",
    "animal-companions": "Command animal companions in combat",
    "skate-tricks": "Land skateboard tricks, grinds, and manuals",
    "sports-goals": "Score goals against computer opponents",
    "extraction-runs": "Loot and extract with your gear",
    pistols: "Shoot with pistols",
    rifles: "Shoot with rifles",
    bows: "Shoot with bows",
    "melee-weapons": "Fight with melee weapons",
    "fist-fights": "Fight with your fists",
    "space-exploration": "Explore other planets",
    swimming: "Swim and dive",

    "open-world": "Explore an open world",
    "missions-or-levels": "Complete missions or levels",
    "rounds-or-matches": "Play rounds or matches",
    combat: "Fight enemies",
    "boss-fights": "Face boss fights",
    stealth: "Sneak past enemies",
    "equipment-loadouts": "Change equipment or loadouts",
    puzzles: "Solve puzzles",
    building: "Build or place structures",
    crafting: "Craft items",
    fishing: "Catch fish",
    cooking: "Prepare meals",
    "farming-or-care": "Tend plants, animals, or characters",
    "driving-or-racing": "Drive vehicles or race",
    "advanced-traversal": "Climb, glide, or perform movement tricks",
    customization: "Change appearances or outfits",
    "photo-mode": "Take pictures in photo mode",
    "online-teamplay": "Play together online",
    "local-multiplayer": "Play together on one device",
    collectibles: "Find collectibles",
    "choices-or-lore": "Read lore or follow dialogue",
  },
  personalTitle: "Your own library",
  personalDescription:
    "Add the games you play. You can change this later from your profile.",
  devStartDescription:
    "{{count}} games and series. Jump straight to your mood.",
  personalStartDescription:
    "Pick from the collection or add any game you like.",
  continueWithoutGames: "Start with any-game quests",
  backToStart: "Back",
  backToLibrary: "Back to library",
  collectionHint:
    "Quests made for these games. Pick the entries you play, then choose whether to add flexible quests too.",
  addAll: "Add all",
  removeAll: "Remove all",
  searchGames: "Find a game or series",
  game: "Game",
  series: "Series",
  noSearchResults: "No match in the collection. Add your game below.",
  editGame: "Edit {{game}}",
  removeGame: "Remove {{game}}",
  confirmRemove: "Remove?",
  appearance: "Icon",
  reviewSelection: "Your quest selection",
  searchQuests: "Find a quest",
  showMatched: "Show matched quests",
  showAllReusable: "Browse all reusable quests",
  resetMatches: "Reset to feature matches",
  noActivityResults: "No activities match this search.",
  noQuestResults: "No quests match this search.",
  colorNames: {
    relax: "Mint",
    explore: "Amber",
    progress: "Blue",
    create: "Pink",
    challenge: "Coral",
    connect: "Lime",
    nostalgic: "Lilac",
    overwhelmed: "Peach",
    restless: "Yellow",
    focused: "Indigo",
    curious: "Turquoise",
    "low-energy": "Slate",
  },
};

export const germanLibrary = {
  welcome: "Willkommen bei",
  welcomeDescription:
    "Eine kleine Starthilfe für alle mit zu vielen Videospielen.",
  moreInformation: "Mehr Informationen",
  changeLanguage: "Sprache ändern",
  changeTheme: "Theme ändern",
  changeThemeTo: "Theme zu {{theme}} ändern",
  closeInformation: "Informationen schließen",
  createLibrary: "Eigene Bibliothek erstellen",
  startWithoutSetup: "Ohne Einrichtung starten",
  overviewIntro: "Wähle Spiele aus der Starter-Sammlung oder füge eigene hinzu",
  finishSetup: "Einrichtung abschließen",
  optional: "Optional",
  configureGame: "Spiel- & Quest-Optionen",
  editorIntro:
    "Gib deinem Spiel einen Namen und Look und wähle dann seine Aktivitäten",
  activitiesIntro: "Wähle alles aus, was man in",
  possibleActivities: "Mögliche Aktivitäten",
  adjust: "Anpassen",
  chooseActivities: "Wähle aus, was man in diesem Spiel machen kann.",
  addActivities: "Aktivitäten hinzufügen",
  saveActivities: "Aktivitäten speichern",
  saveLibrary: "Bibliothek speichern",
  editGameTitle: "Spiel bearbeiten",
  selectActivities: "Aktivitäten auswählen",
  activitiesView: "Aktivitäten",
  questsView: "Quests",
  activityView: "Aktivitäten oder Quests anzeigen",
  drawerActivitiesIntro: "Wähle alles aus, was du in",
  drawerActivitiesOutro:
    " machen kannst. Daraus werden später deine persönlichen sidequests.",
  selectedActivities: "{{count}} ausgewählt",
  selectedQuests: "{{count}} Quests ausgewählt",
  searchActivities: "Suche",
  back: "Zurück",
  done: "Fertig",
  previousIcons: "Vorherige Icons",
  nextIcons: "Nächste Icons",
  moreColors: "Weitere Farben",
  previousColors: "Vorherige Farben",
  iconPage: "Icon-Seite {{page}}",
  previewRelax: "Entspannung",
  previewNostalgia: "Nostalgie",
  scrollDown: "Weiter nach unten",

  setupEyebrow: "Dein Spieleregal",
  setupTitle: "Willkommen auf sidesidequest",
  setupDescription:
    "Starte mit einer ausgewählten Spielesammlung oder erstelle deine eigene.",
  curatedHeading: "Starter-Sammlung",
  supportedGames: "Unterstützte Spiele",
  noCuratedGames: "Keine Starter ausgewählt",
  selectGame: "Spiel auswählen",
  saveSelection: "Speichern",
  curatedDescription: "Spiele und Reihen mit eigenen Quests.",
  questMode: "Quests für {{game}}",
  curatedOnly: "Nur kuratierte",
  curatedAndFlexible: "Kuratierte + flexible",
  installments: "Unterstütze Teile",
  chooseInstallment:
    "Wähle mindestens einen Teil, um passende Quests zu bekommen.",
  customHeading: "Deine Spiele",
  customDescription:
    "Füge ein beliebiges Spiel hinzu und wähle die Aktivitäten für seine Quests.",
  addGame: "Spiel hinzufügen",
  add: "Hinzufügen",
  saveGame: "Spiel speichern",
  cancel: "Abbrechen",
  edit: "Bearbeiten",
  remove: "Entfernen",
  untitledGame: "Dein Spiel",
  gameName: "Name des Spiels oder der Reihe",
  gameNamePlaceholder: "Spielname",
  gameIcon: "Icon",
  gameColor: "Farbe",
  iconChoice: "Icon {{icon}} verwenden",
  colorChoice: "Farbe {{color}} verwenden",
  capabilities: "Was kann man im Spiel machen?",
  capabilitiesHint:
    "Aktivitäten finden flexible Quests, die zu diesem Spiel passen. Vor dem Speichern kannst du jeden Treffer prüfen.",
  reviewQuests: "Quests ansehen",
  reviewQuestsHint:
    "Entferne unpassende Quests für dieses Spiel. Du kannst auch alle flexiblen Quests durchsuchen und nur einzelne hinzufügen.",
  questCount_one: "{{count}} Quest",
  questCount_other: "{{count}} Quests",
  capabilityCount_one: "{{count}} Feature",
  capabilityCount_other: "{{count}} Features",
  noCustomGames: "Noch keine eigenen Spiele.",
  setupSelection_one: "{{count}} Spiel ausgewählt",
  setupSelection_other: "{{count}} Spiele ausgewählt",
  startSidequests: "Sidequests starten",
  drawerTitle: "Spielebibliothek",
  drawerDescription: "Deine Spiele, Reihen und die passenden Quests.",
  profileSummaryCounts: "{{curated}} kuratierte / {{custom}} eigene Spiele",
  profileSummary: "Spiele auswählen und einrichten",
  icons: {
    zombie: "Zombie",
    vampire: "Vampir",
    "slasher-mask": "Horrormaske",
    "haunted-house": "Spukhaus",
    ghost: "Geist",
    castle: "Burg",
    space: "Weltraum",
    radiation: "Radioaktivität",

    action: "Action",
    adventure: "Abenteuer",
    arcade: "Arcade",
    building: "Bauen",
    cards: "Karten",
    cozy: "Gemütlich",
    exploration: "Erkundung",
    fighting: "Kampfspiel",
    horror: "Horror",
    multiplayer: "Multiplayer",
    platformer: "Platformer",
    puzzle: "Rätsel",
    racing: "Rennspiel",
    rhythm: "Rhythmus",
    rpg: "Rollenspiel",
    shooter: "Shooter",
    simulation: "Simulation",
    sports: "Sport",
    strategy: "Strategie",
    survival: "Survival",
    boss: "Bosskämpfe",
    stealth: "Schleichen",
    equipment: "Ausrüstung",
    crafting: "Herstellen",
    fishing: "Angeln",
    cooking: "Kochen",
    farming: "Pflanzen und Pflege",
    customization: "Outfits",
    photography: "Fotomodus",
    "local-co-op": "Lokaler Koop",
    collectibles: "Sammelobjekte",
    lore: "Geschichten und Spielwelt",
  },
  capabilityLabels: {
    magic: "Im Kampf zaubern",
    trading: "Gegenstände kaufen und verkaufen",
    hunting: "Tiere für Materialien jagen",
    "animal-companions": "Tierbegleitern im Kampf Befehle geben",
    "skate-tricks": "Skateboard-Tricks, Grinds und Manuals landen",
    "sports-goals": "Tore gegen Computergegner erzielen",
    "extraction-runs": "Beute sammeln und mit Ausrüstung extrahieren",
    pistols: "Mit Pistolen schießen",
    rifles: "Mit Gewehren schießen",
    bows: "Mit Bögen schießen",
    "melee-weapons": "Mit Nahkampfwaffen kämpfen",
    "fist-fights": "Faustkämpfe bestreiten",
    "space-exploration": "Fremde Planeten erkunden",
    swimming: "Schwimmen und tauchen",

    "open-world": "Eine offene Welt erkunden",
    "missions-or-levels": "Missionen oder Level abschließen",
    "rounds-or-matches": "Runden oder Matches spielen",
    combat: "Gegen Gegner kämpfen",
    "boss-fights": "Bosskämpfe bestreiten",
    stealth: "An Gegnern vorbeischleichen",
    "equipment-loadouts": "Ausrüstung oder Loadouts wechseln",
    puzzles: "Rätsel lösen",
    building: "Bauen oder Objekte platzieren",
    crafting: "Gegenstände herstellen",
    fishing: "Fische fangen",
    cooking: "Mahlzeiten zubereiten",
    "farming-or-care": "Pflanzen, Tiere oder Figuren versorgen",
    "driving-or-racing": "Fahrzeuge steuern oder Rennen fahren",
    "advanced-traversal": "Klettern, gleiten oder Bewegungstricks nutzen",
    customization: "Aussehen oder Outfits ändern",
    "photo-mode": "Bilder im Fotomodus aufnehmen",
    "online-teamplay": "Online zusammen spielen",
    "local-multiplayer": "An einem Gerät zusammen spielen",
    collectibles: "Sammelobjekte finden",
    "choices-or-lore": "Hintergrundtexte lesen oder Dialogen folgen",
  },
  personalTitle: "Deine eigene Bibliothek",
  personalDescription:
    "Füge die Spiele hinzu, die du spielst. Du kannst das später im Profil ändern.",
  devStartDescription:
    "{{count}} Spiele und Reihen. Direkt zur Stimmungsauswahl.",
  personalStartDescription:
    "Wähle aus der Sammlung oder füge ein beliebiges Spiel hinzu.",
  continueWithoutGames: "Mit Quests für beliebige Spiele starten",
  backToStart: "Zurück",
  backToLibrary: "Zur Bibliothek",
  collectionHint: "Eine Auswahl von Spielen und Reihen mit eigenen Quests",
  addAll: "Alle hinzufügen",
  removeAll: "Alle entfernen",
  searchGames: "Spiel oder Reihe suchen",
  game: "Spiel",
  series: "Reihe",
  noSearchResults: "Kein Treffer in der Sammlung. Füge dein Spiel unten hinzu.",
  editGame: "{{game}} bearbeiten",
  removeGame: "{{game}} entfernen",
  confirmRemove: "Entfernen?",
  appearance: "Icon",
  reviewSelection: "Deine Quest-Auswahl",
  searchQuests: "Quest suchen",
  showMatched: "Passende Quests zeigen",
  showAllReusable: "Alle wiederverwendbaren Quests",
  resetMatches: "Nach Features zurücksetzen",
  noActivityResults: "Keine Aktivitäten für diese Suche.",
  noQuestResults: "Keine Quests für diese Suche.",
  colorNames: {
    relax: "Mint",
    explore: "Bernstein",
    progress: "Blau",
    create: "Pink",
    challenge: "Koralle",
    connect: "Limette",
    nostalgic: "Flieder",
    overwhelmed: "Pfirsich",
    restless: "Gelb",
    focused: "Indigo",
    curious: "Türkis",
    "low-energy": "Schiefer",
  },
};
