export const germanQuestNames = {
  "relax-soft-landing": "Kindheitsgefühl",
  "relax-scenic-route": "Muskelgedächtnis",
  "relax-care-shift": "Vertrauter Soundtrack",
  "relax-one-good-loop": "Lieblingsort",
  "relax-small-wonder": "Vergessener Favorit",
  "relax-three-loose-ends": "Lieblingsserie",
  "relax-next-save": "Weiter? Ja",
  "relax-gentlest-mode": "Weniger Druck",
  "relax-pause-anytime": "Jederzeit pausierbar",
  "relax-turn-by-turn": "Geduldige Taktik",
  "relax-easy-victory": "Leichter Sieg",
  "relax-quietest-game": "Ruhigstes Spiel",
  "relax-tend-one-thing": "Kleine Fürsorge",
  "relax-put-things-right": "Ein Bereich in Ordnung",
  "relax-slow-journey": "Langsame Reise",
  "relax-story-carries-you": "Sanftes Abenteuer",
  "relax-one-puzzle": "Ruhiges Rätsel",
  "relax-friendly-face": "Freundliches Gesicht",
  "relax-solo-room": "Ungestörte Session",
  "relax-forgiving-restart": "Verzeihender Neustart",
  "relax-soft-colors": "Sanfte Farbwelt",
  "relax-good-weather": "Besseres Wetter",
  "relax-small-routine": "Beruhigende Routine",
  "relax-watch-and-wander": "Ruhiges Umherstreifen",
  "relax-one-button-deeper": "Ein Knopf",
  "relax-safe-home-base": "Heimatbasis",
  "relax-low-volume": "Leise gespielt",
  "relax-kindest-save-file": "Ruhiger Spielstand",
  "relax-comforting-repetition": "Lieblingsroutine",
  "relax-clean-exit": "Sauberer Abschluss",
  "relax-cozy-corner": "Gemütliche Ecke",
  "relax-fishing-break": "Angelpause",
  "relax-quiet-drive": "Ruhige Fahrt",
  "relax-gentle-platformer": "Sanftes Plattformspiel",
  "relax-solo-tabletop": "Solo-Brettspiel",
  "relax-space-drift": "Weltraumdrift",

  "explore-wrong-turn": "Dritte Wahl",
  "explore-follow-the-signal": "Jenseits der Erde",
  "explore-edge-of-known": "Tor zur Fantasie",
  "explore-mechanic-safari": "Neonstadt",
  "explore-landmark-navigation": "In die Wildnis",
  "explore-behind-the-obvious": "Wüstendurchquerung",
  "explore-below-surface": "Unter der Oberfläche",
  "explore-world-underfoot": "Welt im Untergrund",
  "explore-borrowed-body": "Tierperspektive",
  "explore-other-camera": "Kommandoperspektive",
  "explore-genre-detour": "Genre-Abstecher",
  "explore-physical-rule": "Ungewöhnliche Steuerung",
  "explore-follow-clue": "Ein Hinweis",
  "explore-command-view": "Ganzes Spielfeld",
  "explore-play-by-ear": "Nach Gehör",
  "explore-movement-language": "Neue Bewegung",
  "explore-words-have-weight": "Worte mit Gewicht",
  "explore-small-world-big-idea": "Kleines seltsames Spiel",
  "explore-never-same-twice": "Neuer Run",
  "explore-one-word-door": "Kürzester Titel",
  "explore-color-beacon": "Farbsignal",
  "explore-earliest-release": "Früher Klassiker",
  "explore-genre-collision": "First-Person-Logik",
  "explore-no-straight-line": "Freie Route",
  "explore-failure-teaches": "Nützliche Niederlage",
  "explore-unusual-job": "Seltsame Schicht",
  "explore-without-combat": "Friedlicher Fortschritt",
  "explore-scale-shift": "Maßstabswechsel",
  "explore-rule-you-doubt": "Prämissentest",
  "explore-opposite-choice": "Anderer Instinkt",
  "explore-immersive-sim": "Immersives Experiment",
  "explore-metroidvania-shortcut": "Versteckte Abkürzung",
  "explore-archaeology-trail": "Alte Spuren",
  "explore-unfamiliar-cockpit": "Neues Cockpit",
  "explore-tiny-world": "Kleine Welt",
  "explore-wordless-world": "Wortlose Welt",

  "progress-break-the-blocker": "Ungespielter Start",
  "progress-clean-finish": "Faire Chance",
  "progress-one-tier-better": "Aufgegebener Spielstand",
  "progress-three-step-plan": "Shooter-Freischaltung",
  "progress-recovery-run": "Nächste Kampagne",
  "progress-two-birds": "Installierter Kandidat",
  "progress-wake-the-sleeping-save": "Ältester Spielstand",
  "progress-honor-the-oldest-promise": "Älteste Quest",
  "progress-open-the-black-box": "Systemdurchbruch",
  "progress-revisit-the-wall": "Rätseldurchbruch",
  "progress-clear-one-map-pocket": "Kartenausschnitt",
  "progress-open-the-expansion-door": "Erweiterungstür",
  "progress-let-the-other-hero-grow": "Andere Figur",
  "progress-rebuild-muscle-memory": "Steuerung neu gelernt",
  "progress-follow-the-remembered-thread": "Erinnerter Handlungsstrang",
  "progress-shake-off-the-rust": "Rost abgeschüttelt",
  "progress-claim-the-nearby-feat": "Achievement Get",
  "progress-return-to-the-gift": "Geschenktes Spiel",
  "progress-choose-the-short-road": "Kurze Kampagne",
  "progress-cross-the-middle": "Fortschritt im Mittelteil",
  "progress-unpack-and-move": "Inventar entlastet",
  "progress-prove-one-technique": "Verlässliche Technik",
  "progress-play-the-missing-link": "Fehlende Fortsetzung",
  "progress-earn-the-specific-upgrade": "Nahes Upgrade",
  "progress-remove-one-barrier": "Hürde entfernt",
  "progress-finish-a-favorites-loose-end": "Offene Lieblingsaufgabe",
  "progress-take-the-road-not-used": "Anderer Zweig",
  "progress-rescue-the-secondary-save": "Zweiter Spielstand",
  "progress-transfer-a-strength": "Übertragene Fähigkeit",
  "progress-spend-the-hoarded-resource": "Gehorteter Vorrat",
  "progress-finish-the-tutorial": "Tutorial abgeschlossen",
  "progress-roguelike-meta-step": "Roguelike-Fortschritt",
  "progress-complete-a-season": "Saisonfinale",
  "progress-open-the-endgame": "Endspiel geöffnet",
  "progress-master-one-recipe": "Rezept gemeistert",
  "progress-fix-one-crisis": "Krise gelöst",

  "create-new-build-old-parts": "Leere Fläche",
  "create-function-first": "Figuren-Makeover",
  "create-rule-of-three": "Funktionierende Maschine",
  "create-strategy-remix": "Build-Remix",
  "create-make-a-landmark": "Spielbarer Ort",
  "create-before-and-after": "Fotospaziergang",
  "create-tell-a-room-sized-story": "Geschichte im Raum",
  "create-make-the-useful-prototype": "Nützlicher Prototyp",
  "create-build-around-the-flaw": "Darum herum gebaut",
  "create-design-one-livable-block": "Lebenswerter Block",
  "create-shape-a-seasonal-garden": "Saisonaler Garten",
  "create-dress-for-an-npc": "NPC-Stil",
  "create-take-an-honest-portrait": "Ruhiges Porträt",
  "create-chase-one-kind-of-light": "Eine Art Licht",
  "create-stage-a-three-frame-story": "Drei-Bilder-Geschichte",
  "create-curate-the-odd-shelf": "Ungewöhnliche Sammlung",
  "create-build-a-creatures-home": "Zuhause für ein Wesen",
  "create-embrace-one-sided-balance": "Bewusste Asymmetrie",
  "create-run-a-kind-economy": "Faire Wirtschaft",
  "create-invent-a-team-identity": "Teamidentität",
  "create-roleplay-a-local": "Gewöhnlicher Alltag",
  "create-solve-it-sideways": "Ungewöhnliche Lösung",
  "create-draw-with-a-route": "Gezeichnete Route",
  "create-compose-a-place-theme": "Ortsthema",
  "create-sculpt-for-one-view": "Ein Blickwinkel",
  "create-repair-with-a-new-idea": "Kreation repariert",
  "create-stage-a-silent-scene": "Stille Szene",
  "create-design-for-the-smallest-user": "Langsamster Reisender",
  "create-invent-a-personal-ritual": "Persönliches Ritual",
  "create-leave-a-kind-trace": "Gute Spur",
  "create-boss-arena": "Boss-Arena",
  "create-themed-deck": "Themendeck",
  "create-accessible-route": "Barrierefreie Route",
  "create-racing-livery": "Rennlackierung",
  "create-factory-blueprint": "Wiederverwendbarer Bauplan",
  "create-character-backstory": "Hintergrundgeschichte",

  "challenge-first-try-counts": "Fighting-Set",
  "challenge-one-step-harder": "Shooter-Trio",
  "challenge-beat-your-ghost": "Drei-Rennen-Test",
  "challenge-pressure-proof": "Gegner gelesen",
  "challenge-thin-margin": "Volles Sportmatch",
  "challenge-adapt-on-contact": "Persönliche Bestleistung",
  "challenge-return-to-the-wall": "Noch einmal die Hürde",
  "challenge-one-notch-higher": "Eine Stufe höher",
  "challenge-three-life-window": "Drei Leben",
  "challenge-neglected-tool": "Vernachlässigtes Werkzeug",
  "challenge-silent-route": "Unentdeckter Weg",
  "challenge-rationed-run": "Halbe Vorräte",
  "challenge-boss-rematch": "Git Gud, aber fair",
  "challenge-precision-passage": "Präzisionspassage",
  "challenge-no-hint-hour": "Ohne Hinweise",
  "challenge-weak-link-drill": "Schwachstelle trainiert",
  "challenge-daily-trial": "Tagesherausforderung",
  "challenge-underdog-kit": "Außenseiterwahl",
  "challenge-no-restart-recovery": "Erholung ohne Neustart",
  "challenge-pattern-reader": "Muster erkannt",
  "challenge-last-stand": "Drei Wellen",
  "challenge-ranked-nerves": "Ranglistennerven",
  "challenge-nearby-achievement": "Schwerer Erfolg",
  "challenge-survival-shift": "Ganze Schicht",
  "challenge-one-mechanic-master": "Fortgeschrittene Technik",
  "challenge-clean-combo": "Saubere Sequenz",
  "challenge-damage-budget": "Schadensbudget",
  "challenge-unknown-ruleset": "Unbekannte Regeln",
  "challenge-audacious-route": "Riskanter Weg",
  "challenge-tension-you-avoid": "Spannung ausgehalten",
  "challenge-platformer-no-fall": "Abschnitt ohne Sturz",
  "challenge-tactics-iron-plan": "Eiserner Plan",
  "challenge-rhythm-clean-song": "Sauberer Song",
  "challenge-sports-comeback": "Comeback-Spiel",
  "challenge-extraction-one-haul": "Nützliche Beute",
  "challenge-speedrun-one-split": "Speedrun-Split",

  "connect-lift-the-lowest": "Altes Squad",
  "connect-follow-their-lead": "Neues Team",
  "connect-share-the-upgrade": "Vertraute Empfehlung",
  "connect-rescue-route": "Offene Kooperation",
  "connect-set-up-the-finish": "Gemeinsame Welt",
  "connect-trade-roles": "Wahl der anderen Person",
  "connect-global-ghost": "Spieler-Geist",
  "connect-daily-crowd": "Offenes Turnier",
  "connect-player-made-door": "Community-Level",
  "connect-leave-a-signal": "Unsichtbare Hilfe",
  "connect-shared-save-return": "Gemeinsamer Spielstand",
  "connect-watched-first": "Zuerst zugeschaut",
  "connect-creator-signature": "Kreative Handschrift",
  "connect-showpiece-session": "Vorzeigespiel",
  "connect-community-mod": "Community-Remix",
  "connect-same-seed": "Geteilter Seed",
  "connect-common-language": "Gemeinsamer Modus",
  "connect-friends-leaderboard": "Bekannte Punktzahl",
  "connect-asynchronous-turn": "Asynchroner Zug",
  "connect-community-build": "Gemeinsames Bauwerk",
  "connect-replay-company": "Lektion aus der Wiederholung",
  "connect-pass-it-on": "Empfehlung bereit",
  "connect-quiet-lobby": "Stille Lobby",
  "connect-borrow-their-style": "Übernommener Stil",
  "connect-community-tactic": "Community-Taktik",
  "connect-fandom-doorway": "Gemeinsames Fandom",
  "connect-small-kindness": "Kleine Hilfe",
  "connect-parallel-company": "Begleitende Stimme",
  "connect-memory-reconstruction": "Gemeinsame Erinnerung",
  "connect-one-viewer-clip": "Teilbarer Moment",
  "connect-couch-handoff": "Geteilter Controller",
  "connect-party-lobby": "Party-Lobby",
  "connect-public-event": "Öffentliches Event",
  "connect-trade-a-gift": "Nützliches Geschenk",
  "connect-coop-puzzle": "Koop-Rätsel",
  "connect-support-the-lowest": "Unterstützung fürs Schlusslicht",

  "first-game-memory": "Erste Spielerinnerung",
  "menu-music-door": "Menümusik",
  "old-console-era": "Frühere Konsole",
  "series-beginning": "Erstes Kapitel",
  "forgotten-save": "Zeitkapsel-Spielstand",
  "childhood-coop-solo": "Zweiter Controller",
  "first-hard-win": "Alter Triumph",
  "rental-weekend": "Geliehenes Wochenende",
  "demo-memory": "Vertrauter Anfang",
  "old-avatar": "Alte Figur",
  "lost-mode": "Verlorener Modus",
  "remembered-map": "Erinnerte Karte",
  "credits-memory": "Denkwürdiges Ende",
  "licensed-childhood": "Samstagmorgen",
  "handheld-evening": "Handheld-Abend",
  "seasonal-memory": "Saisonale Erinnerung",
  "family-game": "Familienklassiker",
  "old-friend-pick": "Empfehlung eines Freundes",
  "retired-strategy": "Alte Strategie",
  "classic-roster": "Vertraute Aufstellung",
  "old-racing-line": "Erinnerte Ideallinie",
  "first-rpg-town": "Erste RPG-Stadt",
  "old-horror-courage": "Alter Schrecken",
  "dated-save-name": "Ältester Zeitstempel",
  "dormant-achievement": "Ein Achievement fehlt",
  "original-vs-remaster": "Remake-Rückkehr",
  "original-settings": "Alte Einstellungen",
  "muscle-memory-mechanic": "Erinnerte Bewegung",
  "legacy-character": "Früherer Main",
  "one-last-revisit": "Letzte Rückkehr",
  "nostalgic-arcade-credit": "Insert Coin",
  "nostalgic-cheat-code": "Bekannter Cheat",
  "nostalgic-first-indie": "Frühes Indie-Spiel",
  "nostalgic-old-customization": "Alter Look",
  "nostalgic-startup-sounds": "Startsound",
  "nostalgic-old-guide-memory": "Geheimnis aus Erinnerung",

  "smallest-install": "Kleinste Installation",
  "shortest-promised-time": "Kürzeste Aktivität",
  "no-setup-needed": "Ohne Vorbereitung",
  "nearest-checkpoint": "Nächster Kontrollpunkt",
  "fewest-buttons": "Wenigste Tasten",
  "first-installed-row": "Erste Reihe",
  "one-letter-shelf": "Ein Buchstabe",
  "single-cover-pull": "Blaues Cover",
  "safe-mode": "Geringster Druck",
  "no-inventory-session": "Inventar geschlossen",
  "one-marker-only": "Nahe Markierung",
  "closest-completion": "Nächster Abschluss",
  "tutorial-free": "Vertraute Steuerung",
  "single-screen-game": "Ein Bildschirm",
  "pause-guaranteed": "Nächster Autosave",
  "no-dialogue-choice": "Geschichte entscheidet",
  "one-match-contract": "Ein Match",
  "one-room-boundary": "Ein Raum",
  "single-verb": "Einfachste Aktion",
  "visible-timer": "Ausstieg festgelegt",
  "platform-recent": "Zuletzt gespielt",
  "controller-ready": "Controller bereit",
  "no-update-door": "Kein Download",
  "familiar-interface": "Vertraute Menüs",
  "one-save-only": "Bestehender Spielstand",
  "finite-run": "Begrenztes Rätselset",
  "default-build": "Standard-Loadout",
  "default-difficulty": "Empfohlene Schwierigkeit",
  "fewest-open-threads": "Ruhigster Spielstand",
  "stop-rule-first": "Ausstieg zuerst",
  "overwhelmed-quick-resume": "Schnell fortgesetzt",
  "overwhelmed-saved-preset": "Gespeicherte Voreinstellung",
  "overwhelmed-last-level": "Letztes Level",
  "overwhelmed-first-tutorial": "Ein Tutorial",
  "overwhelmed-shortest-description": "Mittlere Wahl",
  "overwhelmed-featured-daily": "Hervorgehobene Tagesaufgabe",

  "instant-movement": "Sofort in Bewegung",
  "speed-line": "Schnelle Linie",
  "destruction-break": "Große Zerstörung",
  "rhythm-release": "Rhythmusrausch",
  "short-rogue-run": "Schneller Roguelike-Run",
  "parkour-route": "Parkour-Route",
  "arena-sprint": "Schnellste Arena",
  "combo-chase": "Laufende Combo",
  "chase-sequence": "Verfolgung beendet",
  "boss-now": "Direkt zum Boss",
  "sports-quarter": "Ein Spielabschnitt",
  "flight-loop": "Abheben",
  "vehicle-switch-off": "Ein Fahrzeug",
  "swarm-clear": "Schwarm beseitigt",
  "timed-objective": "Countdown geschlagen",
  "movement-only-win": "Sieg durch Positionierung",
  "loudest-game": "Energiegeladener Soundtrack",
  "quick-reaction": "Reiner Reflex",
  "vertical-climb": "Höhere Aussicht",
  "trick-session": "Neuer Trick",
  "rapid-puzzle": "Rätsel in Bewegung",
  "aggressive-route": "Direkter Weg",
  "mech-weight": "Schwere Maschine",
  "crowd-route": "Durch die Menge",
  "streak-attempt": "Dreierserie",
  "escape-the-hub": "Raus aus dem Hub",
  "one-life-motion": "Bewegung bis zum Ende",
  "role-with-tempo": "Teamtempo",
  "physical-finish": "Bewegter Abschluss",
  "restless-landing": "Letzter Energieschub",
  "restless-twin-stick": "Twin-Stick-Arena",
  "restless-hack-and-slash": "Hack-and-Slash-Raum",
  "restless-pinball-table": "Flipperrunde",
  "restless-skate-line": "Skate-Line",
  "restless-beat-em-up": "Beat-'Em-up-Etappe",
  "restless-rts-rush": "Zerg Rush",

  "single-campaign-thread": "Handlungsstrang",
  "deep-puzzle": "Schwieriges Rätsel",
  "boss-study": "Bossstudie",
  "build-one-function": "Funktionierendes System",
  "achievement-line": "Erfolgsweg",
  "chapter-with-notes": "Story-Kapitel",
  "one-deck-session": "Unverändertes Deck",
  "one-character-session": "Eine Figur",
  "collectible-set": "Sammelset",
  "route-mastery": "Route gemeistert",
  "skill-lab": "Zugtraining",
  "one-city-block": "Stadtblock",
  "questline-only": "Benannte Questreihe",
  "ranked-set": "Wettkampfset",
  "craft-one-object": "Fertiges Objekt",
  "photo-one-subject": "Ein Motiv",
  "strategy-one-plan": "Eine Strategie",
  "language-immersion": "Jeder Hinweis",
  "save-rescue": "Spielstand gerettet",
  "economy-balance": "Stabile Wirtschaft",
  "one-dungeon": "Ein Dungeon",
  "single-soundscape": "Ein Klangraum",
  "one-conversation-tree": "Figurenstudie",
  "precision-score": "Eine Zahl",
  "map-pocket": "Kleine Region",
  "system-experiment": "Eine Variable",
  "one-room-makeover": "Raum fertig",
  "credits-push": "Abschlussbildschirm",
  "manual-mastery": "System verstanden",
  "focus-cooldown": "Sauberes Ende",
  "focused-grand-strategy-turn": "Nur noch ein Zug",
  "focused-factory-bottleneck": "Fabrikengpass",
  "focused-flight-procedure": "Vollständiger Ablauf",
  "focused-detective-case": "Fall abgeschlossen",
  "focused-rhythm-set": "Rhythmus-Set",
  "focused-speedrun-segment": "Speedrun-Segment",

  "strangest-installed": "Seltsamstes Cover",
  "untried-mechanic": "Ungewohnte Aktion",
  "genre-hybrid": "Genre-Kollision",
  "unknown-developer": "Unbekannter Entwickler",
  "physics-question": "Physikfrage",
  "unread-lore-object": "Übersehene Geschichte",
  "npc-routine": "NPC-Routine",
  "alternate-camera": "Andere Perspektive",
  "procedural-surprise": "Neue Welt",
  "community-mod": "Spielervariante",
  "accessibility-transform": "Veränderte Ausgabe",
  "language-switch": "Andere Sprache",
  "oldest-untouched": "Ältestes ungespieltes Spiel",
  "one-star-review-question": "Zweiter Eindruck",
  "unusual-protagonist": "Ungewöhnliche Hauptfigur",
  "side-system": "Nebensystem",
  "soundtrack-before-cover": "Nach Klang gewählt",
  "forgotten-demo": "Früheres Testspiel",
  "mechanic-without-tutorial": "Regel zuerst",
  "map-edge": "Abseits der Route",
  "object-history": "Geschichte des Objekts",
  "ruleset-random": "Unbekannter Regelsatz",
  "opposite-dialogue": "Gegenteilige Antwort",
  "small-studio": "Mikrospielsammlung",
  "historical-setting": "Unbekannte Epoche",
  "future-rule": "Unmögliche Technologie",
  "hidden-ending-door": "Alternativer Ausgang",
  "player-made-level": "Entwicklerkommentar",
  "one-system-collision": "Systemkollision",
  "curiosity-souvenir": "Sichtbares Wahrzeichen",
  "curious-non-euclidean": "Die Karte lügt",
  "curious-ecology-sim": "Lebendes System",
  "curious-programming-game": "Programmierte Lösung",
  "curious-fmv-game": "Drück X fürs Drama",
  "curious-text-experiment": "Nur Worte",
  "curious-obscure-sport": "Unbekannte Sportart",

  "bed-friendly": "Bequemer Start",
  "turns-wait": "Geduldige Züge",
  "story-mode": "Geschichtenfluss",
  "auto-support": "Hilfreiche Assists",
  "one-hand-loop": "Minimale Eingabe",
  "visual-novel-scene": "Visual-Novel-Szene",
  "easy-puzzle": "Gemütliches Rätsel",
  "gentle-management": "Kleines System",
  "walking-only": "Spaziergang",
  "familiar-save": "Vertrauter Spielstand",
  "photo-stroll": "Ruhiges Foto",
  "music-and-menu": "Soundtrack-Auszeit",
  "no-failure-mode": "Nichts zu verlieren",
  "one-day-sim": "Ein Spieltag",
  "short-episode": "Story-Episode",
  "cozy-craft": "Nützliches Werkstück",
  "home-base-only": "Menüaufgabe",
  "ambient-company": "Ruhige Begleitung",
  "one-conversation": "Ein Gespräch",
  "slow-vehicle": "Langsame Fahrt",
  "known-puzzle-type": "Vertrautes Rätsel",
  "supportive-role": "Unterstützungsrolle",
  "collect-nearby": "Sammlung in der Nähe",
  "default-everything": "Aktuelle Einstellungen",
  "replay-favorite-level": "Einfache Wiederholung",
  "gentle-weather": "Schöner Sitzplatz",
  "watch-systems": "Systemzyklus",
  "old-tutorial-area": "Sicherer Startbereich",
  "low-reading": "Formen lesen",
  "energy-honest-exit": "Genug ist genug",
  "low-energy-idle-check-in": "Idle-Check-in",
  "low-energy-hidden-object": "Wimmelbildszene",
  "low-energy-solitaire": "Solitaire-Runde",
  "low-energy-auto-battler": "Auto-Battle",
  "low-energy-walking-story": "Walking-Story",
  "low-energy-jrpg-turns": "Rundenkampf",
} as const satisfies Record<string, string>;
