import { englishLibrary, germanLibrary } from "./library";
import { englishGallery, germanGallery } from "./gallery";
import { englishPool, germanPool, englishTimed, germanTimed } from "./pool";
import type { MoodDefinition } from "../data/questTypes";

export const englishUi = {
  gallery: englishGallery,
  pool: englishPool,
  nav: {
    skipToContent: "Skip to content",
    mainNavigation: "Main navigation",
    about: "Info",
    spinLogo: "Spin Sidequest logo",
    profileLabel: "Your profile, {{points}} coins",
    points: "{{points}} coins",
    switchLanguage: "Switch to {{language}}",
    english: "EN",
    german: "DE",
    task: "Task",
  },
  about: {
    title: "Welcome to sidesidequest.",
    description: "A small starting point for people with too many video games.",
    stepsHeading: "How it works",
    step1: "Choose a mood or pick one game for your next quest.",
    step2: "Pick a quest and launch the matching video game",
    step3: "Start the timer and complete the quest in your game.",
    mismatchHeading: "The quest isn't right for you?",
    mismatchBody:
      "Before starting, return to the cards for free. After starting, cutting the rope costs 25 coins. Between the minimum and suggested duration, you can give up for free without rewards. Banning a quest also ends it for free.",
    difficultyBody:
      "Read the full objective before you start. Some quests require a mode, item, mechanic, or a save with enough progress.",
    libraryHeading: "Quests for your library",
    libraryBody:
      "Choose from Eddie’s own games or add any game yourself. Games in Eddie’s Collection have their own quests, plus flexible quests that fit their features.",
    libraryChoice:
      "For a series, select the entries you actually play so installment-specific quests stay accurate. You can edit the library later from your profile. Cards without a named game still work with any library.",
    coinsHeading: "What do I do with the coins?",
    coinEarning: "Ordinary quests earn 10 coins per played minute once you reach the suggested duration, including the time already played. Countdown and Speedrun rewards decrease by 10 coins per minute, reaching zero at their time limit.",
    coinSpending:
      "Cutting the rope costs 25 coins; shuffling costs 10. Your first three shuffles are free, and completing a quest makes your next shuffle free.",
    madeBy: "Made by",
  },
  library: englishLibrary,
  history: {
    title: "Quest history",
    description: "Your completed sidequests, newest first.",
    profileSummary_one: "{{count}} completed quest",
    profileSummary_other: "{{count}} completed quests",
    emptyTitle: "No completed sidequests yet",
    emptyBody: "Completed quests will appear here with their game and result.",
    anyGame: "Any game",
    mood: "Mood",
    duration: "Time",
    reward: "Reward",
    coins: "{{count}} coins",
  },
  task: {
    currentQuest: "Current quest",
    pickerIntro: "Choose a mood that fits, or pick a specific game",
    pickerMode: "Quest selection mode",
    mood: "Mood",
    game: "Game",
    selectGame: "Choose a game",
    changeGame: "Change game",
    chooseGameQuest: "Choose a quest for {{game}}",
    noLibraryGamesTitle: "No playable games selected",
    noLibraryGamesBody:
      "Add a game or select a series installment in your library to draw quests.",
    openLibrary: "Open profile",
    noMatchingQuestsTitle: "No quests for these choices",
    noMatchingQuestsBody:
      "No quests match this choice and your pool settings. Change the game or adjust the pool in your profile.",
    chooseMoodQuest: "Choose a {{mood}} quest",
    selectMood: "Select your mood",
    choosePrefix: "Choose a",
    chooseSuffix: "sidequest",
    changeMood: "Change Mood",
    newCardsLabel: "Shuffle quest cards for free.",
    newCardsPaidLabel: "Shuffle quest cards for {{cost}} coins.",
    newCards: "New cards",
    costsPoints: "costs {{points}}",
    moodCards: "Mood cards",
  },
  offers: {
    deckLabel: "Choose a quest card",
    cardStatus: "Card {{current}} of {{total}}: {{name}}. {{title}}",
    opening: "Opening {{title}}",
    hiddenQuest: "quest",
    revealCard: "Reveal hidden quest card {{number}}",
    selectQuest: "Select {{name}}: {{title}}",
  },
  arc: {
    gameCards: "Game cards",
    curatedQuests_one: "{{count}} curated quest",
    curatedQuests_other: "{{count}} curated quests",
    flexibleQuests_one: "{{count}} flexible quest",
    flexibleQuests_other: "{{count}} flexible quests",
    choose: "Choose",
    center: "Center",
    cardLabel: "{{action}} {{title}}. {{subtitle}}",
    dragOrScroll: "Drag or Scroll",
    status: "{{current}} of {{total}}: {{title}}. {{subtitle}}",
    noCards: "No cards available",
  },
  quest: {
    specialReward: "Special · {{multiplier}}× coins",
    minimumMinutes: "{{count}} min minimum",
    suggestedMinutes: "{{count}} min suggested",
    durationRange: "{{minimum}}–{{suggested}} min",
    durationRangeLong: "{{minimum}}–{{suggested}} minutes",
    durationSingle: "{{count}} min",
    durationSingleLong_one: "{{count}} minute",
    durationSingleLong_other: "{{count}} minutes",
    optionalTwists: "Optional twists",
    activeLabel: "Active {{mood}} quest: {{title}}",
    focusCard: "Focus quest card: {{title}}",
    closeFocusedCard: "Close focused quest card",
    favoriteCardLabel: "Toggle favorite: {{title}}. Double tap to favorite, triple tap to flip, or press Enter or Space to toggle favorite.",
  },
  timer: {
    ...englishTimed,
    elapsed: "Elapsed time {{time}}",
    start: "Start quest timer",
    resume: "Resume quest timer",
    pause: "Pause quest timer",
    unavailable: "Quest timer unavailable",
    ready: "Ready",
    paused: "Paused",
    completeQuest: "Complete quest",
    completeAvailableIn:
      "Complete in <strong>{{time}}</strong>.",
    minimumTryRemaining:
      "Minimum remaining: <strong>{{time}}</strong>.",
    giveUp: "Give up",
    giveUpHint: "End this attempt for free, without rewards.",
    rewardUnlocksAt: "Coins unlock at {{time}} played. You can complete the objective now without coins.",
    noTimedReward: "The reward has reached zero. You can still complete the objective.",
    insufficientCancelCoins: "You don't have enough coins to cancel.",
    cutStopPaid: "Cut the rope to cancel (costs {{cost}} coins).",
    lessThanMinute: "less than a minute",
    coinsEarned: "You receive",
    coinsEarnedLabel: "You receive {{points}} coins",
    yourTime: "Your time",
    pullContinue: "Pull the timer to continue.",
    pullStart: "Pull the timer to start.",
    readyInstructions:
      "Pull the timer to start.<br/>Minimum: <strong>{{time}}</strong>.",
    readyBoundedInstructions:
      "Pull the timer to start.<br/>Minimum: <strong>{{time}}</strong>.",
    pullResume: "Pull the timer to resume.",
    pullPause: "Pull the timer to pause.",
    backToSelection: "Back to selection screen",
    backToSelectionTooltip: "This quest stays open.",
  },
  profile: {
    title: "Your profile",
    pointsLabel: "{{points}} coins",
    points: "Coins",
    description: "Your coins, settings, and completed sidequests.",
    back: "Back to profile",
    yourSidequests: "Your sidequests",
    viewHistory: "View quest history",
    statistics: "Statistics",
    completedQuests: "Completed quests",
    timePlayed: "Time played",
    timePlayedMinutes: "{{minutes}} min",
    timePlayedHours: "{{hours}}h {{minutes}}m",
    coinsCollected: "Coins collected",
    cancelledQuests: "Cancelled quests",
    repeatedQuests: "Repeated quests",
    favoriteMood: "Favorite mood",
    noFavoriteMood: "None yet",
    debugMode: "Developer Mode",
    debugModeDescription: "No minimum duration and cancelling is free",
    debugModeLabel: "Toggle local debug mode",
    debugModeInfoLabel: "About developer mode",
    debugModeOn: "On",
    debugModeOff: "Off",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    themeAuto: "Auto",
    themeLight: "Light",
    themeDark: "Dark",
    sound: "Sound",
    soundLabel: "Toggle sound",
  },
} as const;

type TranslationShape<T> = {
  [Key in keyof T]: T[Key] extends string ? string : TranslationShape<T[Key]>;
};

export const germanUi = {
  gallery: germanGallery,
  pool: germanPool,
  nav: {
    skipToContent: "Zum Inhalt springen",
    mainNavigation: "Hauptnavigation",
    about: "Info",
    spinLogo: "Sidequest-Logo drehen",
    profileLabel: "Dein Profil, {{points}} Münzen",
    points: "{{points}} Münzen",
    switchLanguage: "Zu {{language}} wechseln",
    english: "EN",
    german: "DE",
    task: "Quest",
  },
  about: {
    title: "Willkommen bei sidesidequest.",
    description:
      "Eine kleine Starthilfe für Menschen mit zu vielen Videospielen.",
    stepsHeading: "Wie es funktioniert",
    step1:
      "Wähle eine Stimmung oder ein bestimmtes Spiel für deine nächste Quest.",
    step2: "Such dir eine Quest aus und starte das passende Videospiel dazu",
    step3: "Starte den Timer und schließe die Quest in deinem Spiel ab.",
    mismatchHeading: "Die Aufgabe passt doch nicht?",
    mismatchBody:
      "Vor dem Start kannst du kostenlos zu den Karten zurück. Danach kostet das Durchtrennen des Seils 25 Münzen. Zwischen Mindestzeit und empfohlener Dauer kannst du kostenlos aufgeben, ohne Belohnung. Eine Quest zu verbannen beendet sie ebenfalls kostenlos.",
    difficultyBody:
      "Lies die ganze Aufgabe vor dem Start. Manche Quests brauchen einen Modus, Gegenstand, eine Mechanik oder einen ausreichend fortgeschrittenen Spielstand.",
    libraryHeading: "Quests für deine Bibliothek",
    libraryBody:
      "Wähle Spiele aus Eddies eigener Sammlung oder füg eigene hinzu. Für Eddies Spiele gibt es speziell entwickelte Quests",
    libraryChoice:
      "Bei einer Reihe wählst du die Teile, die du wirklich spielst, damit Quests für einzelne Teile stimmen. Die Bibliothek kannst du später im Profil",
    coinsHeading: "Was mache ich mit den Münzen?",
    coinEarning:
      "Normale Quests geben ab der empfohlenen Dauer 10 Münzen pro gespielter Minute, einschließlich der bisherigen Spielzeit. Bei Countdown und Speedrun sinkt die Belohnung um 10 Münzen pro Minute und erreicht am Zeitlimit null.",
    coinSpending:
      "Das Seil zu durchtrennen kostet 25 Münzen, neu mischen kostet 10. Die ersten drei Mal sind kostenlos. Nach jeder abgeschlossenen Quest ist das nächste Mischen wieder kostenlos.",
    madeBy: "Von",
  },
  library: germanLibrary,
  history: {
    title: "Quest-Verlauf",
    description: "Deine abgeschlossenen Sidequests, die neuesten zuerst.",
    profileSummary_one: "{{count}} abgeschlossene Quest",
    profileSummary_other: "{{count}} abgeschlossene Quests",
    emptyTitle: "Noch keine Sidequest abgeschlossen",
    emptyBody: "Abgeschlossene Quests erscheinen hier mit Spiel und Ergebnis.",
    anyGame: "Beliebiges Spiel",
    mood: "Stimmung",
    duration: "Zeit",
    reward: "Belohnung",
    coins: "{{count}} Münzen",
  },
  task: {
    currentQuest: "Aktuelle Quest",
    pickerIntro: "Wähle eine passende Stimmung oder nur ein bestimmtes Spiel",
    pickerMode: "Quest-Auswahlmodus",
    mood: "Stimmung",
    game: "Spiel",
    selectGame: "Wähle ein Spiel",
    changeGame: "Spiel ändern",
    chooseGameQuest: "Wähle eine Quest für {{game}}",
    noLibraryGamesTitle: "Noch keine spielbaren Titel ausgewählt",
    noLibraryGamesBody:
      "Füge ein Spiel hinzu oder wähle in deiner Bibliothek einen Teil einer Reihe aus, um Quests zu ziehen.",
    openLibrary: "Profil öffnen",
    noMatchingQuestsTitle: "Keine Quests für diese Auswahl",
    noMatchingQuestsBody:
      "Für diese Auswahl und deine Pool-Einstellungen gibt es keine passenden Quests. Ändere das Spiel oder den Quest-Pool im Profil.",
    chooseMoodQuest: "Wähle eine Quest für {{mood}}",
    selectMood: "Wähle deine Stimmung",
    choosePrefix: "Wähle eine",
    chooseSuffix: "-Sidequest",
    changeMood: "Stimmung ändern",
    newCardsLabel: "Quest-Karten kostenlos neu mischen.",
    newCardsPaidLabel: "Quest-Karten für {{cost}} Münzen neu mischen.",
    newCards: "Neue Karten",
    costsPoints: "kostet {{points}}",
    moodCards: "Stimmungskarten",
  },
  offers: {
    deckLabel: "Wähle eine Quest-Karte",
    cardStatus: "Karte {{current}} von {{total}}: {{name}}. {{title}}",
    opening: "{{title}} wird geöffnet",
    hiddenQuest: "Quest",
    revealCard: "Verdeckte Quest-Karte {{number}} aufdecken",
    selectQuest: "{{name}} wählen: {{title}}",
  },
  arc: {
    gameCards: "Spielkarten",
    curatedQuests_one: "{{count}} kuratierte Quest",
    curatedQuests_other: "{{count}} kuratierte Quests",
    flexibleQuests_one: "{{count}} flexible Quest",
    flexibleQuests_other: "{{count}} flexible Quests",
    choose: "Wählen",
    center: "Zentrieren",
    cardLabel: "{{action}}: {{title}}. {{subtitle}}",
    dragOrScroll: "Ziehen oder scrollen",
    status: "{{current}} von {{total}}: {{title}}. {{subtitle}}",
    noCards: "Keine Karten verfügbar",
  },
  quest: {
    specialReward: "Besonders · {{multiplier}}× Münzen",
    minimumMinutes: "mindestens {{count}} Min.",
    suggestedMinutes: "{{count}} Min. empfohlen",
    durationRange: "{{minimum}}–{{suggested}} Min.",
    durationRangeLong: "{{minimum}}–{{suggested}} Minuten",
    durationSingle: "{{count}} Min.",
    durationSingleLong_one: "{{count}} Minute",
    durationSingleLong_other: "{{count}} Minuten",
    optionalTwists: "Optionale Spielvarianten",
    activeLabel: "Aktive Quest für {{mood}}: {{title}}",
    focusCard: "Quest-Karte fokussieren: {{title}}",
    closeFocusedCard: "Fokussierte Quest-Karte schließen",
    favoriteCardLabel: "Favorit umschalten: {{title}}. Zweimal tippen zum Favorisieren, dreimal zum Drehen. Eingabe- oder Leertaste schaltet den Favoriten um.",
  },
  timer: {
    ...germanTimed,
    elapsed: "Vergangene Zeit {{time}}",
    start: "Quest-Timer starten",
    resume: "Quest-Timer fortsetzen",
    pause: "Quest-Timer pausieren",
    unavailable: "Quest-Timer nicht verfügbar",
    ready: "Bereit",
    paused: "Pausiert",
    completeQuest: "Quest abschließen",
    completeAvailableIn:
      "Abschließen in <strong>{{time}}</strong>.",
    minimumTryRemaining:
      "Mindestzeit: noch <strong>{{time}}</strong>.",
    giveUp: "Aufgeben",
    giveUpHint: "Beende diesen Versuch kostenlos, ohne Belohnung.",
    rewardUnlocksAt: "Münzen gibt es ab {{time}} Spielzeit. Du kannst die Aufgabe jetzt ohne Münzen abschließen.",
    noTimedReward: "Die Belohnung hat null erreicht. Du kannst die Aufgabe weiterhin abschließen.",
    insufficientCancelCoins: "Du hast nicht genug Münzen zum Abbrechen.",
    cutStopPaid: "Seil durchtrennen zum Abbrechen (kostet {{cost}} Münzen).",
    lessThanMinute: "weniger als eine Minute",
    coinsEarned: "Du erhältst",
    coinsEarnedLabel: "Du erhältst {{points}} Münzen",
    yourTime: "Deine Zeit",
    pullContinue: "Zieh am Timer, um fortzufahren.",
    pullStart: "Ziehe am Timer, um zu starten.",
    readyInstructions:
      "Zieh am Timer, um zu starten.<br/>Mindestzeit: <strong>{{time}}</strong>.",
    readyBoundedInstructions:
      "Zieh am Timer, um zu starten.<br/>Mindestzeit: <strong>{{time}}</strong>.",
    pullResume: "Ziehe am Timer, um fortzufahren.",
    pullPause: "Ziehe am Timer, um zu pausieren.",
    backToSelection: "Zurück zur Auswahl",
    backToSelectionTooltip: "Die Quest bleibt offen.",
  },
  profile: {
    title: "Dein Profil",
    pointsLabel: "{{points}} Münzen",
    points: "Münzen",
    description: "Deine Münzen, Einstellungen und abgeschlossenen Sidequests.",
    back: "Zurück zum Profil",
    yourSidequests: "Deine Sidequests",
    viewHistory: "Quest-Verlauf ansehen",
    statistics: "Statistiken",
    completedQuests: "Abgeschlossene Quests",
    timePlayed: "Spielzeit",
    timePlayedMinutes: "{{minutes}} Min.",
    timePlayedHours: "{{hours}} Std {{minutes}} Min",
    coinsCollected: "Münzen gesammelt",
    cancelledQuests: "Abgebrochene Quests",
    repeatedQuests: "Wiederholte Quests",
    favoriteMood: "Lieblingsstimmung",
    noFavoriteMood: "Noch keine",
    debugMode: "Developer Mode",
    debugModeDescription: "Keine Mindestzeit und Abbrüche sind gratis",
    debugModeLabel: "Lokalen Debug-Modus umschalten",
    debugModeInfoLabel: "Über den Developer Mode",
    debugModeOn: "An",
    debugModeOff: "Aus",
    settings: "Einstellungen",
    language: "Sprache",
    theme: "Theme",
    themeAuto: "Auto",
    themeLight: "Hell",
    themeDark: "Dunkel",
    sound: "Sound",
    soundLabel: "Sound umschalten",
  },
} as const satisfies TranslationShape<typeof englishUi>;

export const germanMoods = {
  relax: {
    title: "Entspannt",
    subtitle: "Ich möchte bei etwas Vertrautem abschalten und zur Ruhe kommen",
  },
  explore: {
    title: "Entdecken",
    subtitle: "Ich möchte ein Spiel entdecken, das mich noch überraschen kann",
  },
  progress: {
    title: "Fortschritt",
    subtitle: "Ich möchte endlich ein liegen gelassenes Spiel voranbringen",
  },
  create: {
    title: "Kreativ",
    subtitle: "Ich möchte etwas Eigenes erschaffen, das sich nach mir anfühlt",
  },
  challenge: {
    title: "Challenge",
    subtitle: "Ich möchte Widerstand spüren und sehen, was ich schaffen kann",
  },
  connect: {
    title: "Gemeinschaft",
    subtitle: "Ich möchte mich beim Spielen anderen Menschen verbunden fühlen",
  },
  nostalgic: {
    title: "Nostalgie",
    subtitle:
      "Ich möchte zu einem Spiel mit einer guten Erinnerung zurückkehren",
  },
  overwhelmed: {
    title: "Überfordert",
    subtitle: "Ich möchte spielen, kann aber gerade keine Auswahl vertragen",
  },
  restless: {
    title: "Unruhe",
    subtitle: "Ich habe zu viel Energie und muss sie in Bewegung bringen",
  },
  focused: {
    title: "Fokus",
    subtitle: "Ich möchte ganz in ein klares Ziel eintauchen",
  },
  curious: {
    title: "Neugier",
    subtitle: "Ich möchte etwas Unbekanntes ausprobieren und verstehen",
  },
  "low-energy": {
    title: "Wenig Energie",
    subtitle: "Ich möchte ohne viel Aufmerksamkeit oder Anstrengung spielen",
  },
} as const satisfies Record<string, Omit<MoodDefinition, "id">>;
