import { englishLibrary, germanLibrary } from "./library";
import type { MoodDefinition } from "../data/questTypes";

export const englishUi = {
  nav: {
    skipToContent: "Skip to content",
    mainNavigation: "Main navigation",
    about: "Info",
    spinLogo: "Spin Sidequest logo",
    profileLabel: "Your profile, {{points}} coins",
    points: "{{points}} coins",
    switchLanguage: "Switch to {{language}}",
    english: "English",
    german: "German",
    task: "Task",
  },
  about: {
    title: "Welcome to sidesidequest.",
    description: "A small starting point for people with too many video games.",
    stepsHeading: "From choice to play in three steps",
    step1: "Choose how you want to feel while playing",
    step2: "Pick one of three quests for your library or any game",
    step3: "Start the timer, finish the quest, and collect coins",
    mismatchHeading: "The quest isn't right for you?",
    mismatchBody:
      "Before starting, return to the cards for free. Once the timer is running, cut a red rope to cancel the quest.",
    difficultyBody:
      "Read the full objective before you start. Some quests require a mode, item, mechanic, or a save with enough progress.",
    libraryHeading: "Your library, your quests",
    libraryBody:
      "Choose from the starter collection or add any game yourself. Starter games receive their own curated quests plus flexible quests that fit their features.",
    libraryChoice:
      "For a series, select the entries you actually play so installment-specific quests stay accurate. You can edit the library later from your profile. Cards without a named game still work with any library.",
    sourcesHeading: "Where do the ideas come from?",
    sourcesBody:
      "Some quests started with things players shared on Reddit. I check the idea, turn it into a small session, and write the sidequests myself. Others come from exploring what a game lets you do.",
    sourcesButton: "Reddit sources",
    sourcesTitle: "Reddit sources",
    sourcesDescription:
      "The threads behind our research, grouped by game. Each note explains what I took from it. The players did not write or approve our quests.",
    sourcesBack: "Back to Info",
    sourcesOpen: "Open Reddit thread",
    sourcesQuestNames: "Inspired quests",
    sourcesResearchOnly: "Used for background research",
    sourcesLinkHint:
      "Links open Reddit in a new tab. Original thread titles are kept as written.",
    coinsHeading: "What do I do with the coins?",
    coinEarning: "The longer you spend on a quest, the more coins you earn.",
    coinSpending:
      "New cards and extra red ropes cost coins. The idea is to spend a little less time picking and a little more time playing.",
    madeBy: "Made by",
  },
  library: englishLibrary,
  history: {
    title: "Quest history",
    description: "Your completed sidequests, newest first.",
    profileSummary_one: "{{count}} completed quest",
    profileSummary_other: "{{count}} completed quests",
    emptyTitle: "No completed sidequests yet",
    emptyBody: "Completed quests will appear here with their game and result.",
    anyGame: "Any game",
    mood: "Mood",
    duration: "Time",
    reward: "Reward",
    coins: "{{count}} coins",
  },
  task: {
    currentQuest: "Current quest",
    chooseMoodQuest: "Choose a {{mood}} quest",
    selectMood: "Select your mood",
    choosePrefix: "Choose a",
    chooseSuffix: "sidequest",
    changeMood: "Change Mood",
    newCardsLabel:
      "Get new quest cards for {{cost}} coins. {{available}} coins available.",
    newCards: "New cards",
    costsPoints: "costs {{points}}",
    moodCards: "Mood cards",
  },
  offers: {
    deckLabel: "Choose one of three quest cards",
    cardStatus: "Card {{current}} of {{total}}: {{name}}. {{title}}",
    opening: "Opening {{title}}",
    hiddenQuest: "quest",
    revealCard: "Reveal hidden quest card {{number}}",
    selectQuest: "Select {{name}}: {{title}}",
  },
  arc: {
    choose: "Choose",
    center: "Center",
    cardLabel: "{{action}} {{title}}. {{subtitle}}",
    dragOrScroll: "Drag or Scroll",
    status: "{{current}} of {{total}}: {{title}}. {{subtitle}}",
    noCards: "No cards available",
  },
  quest: {
    minimumMinutes: "{{count}} min minimum",
    suggestedMinutes: "{{count}} min suggested",
    durationRange: "{{minimum}}–{{suggested}} min",
    durationRangeLong: "{{minimum}}–{{suggested}} minutes",
    durationSingle: "{{count}} min",
    durationSingleLong_one: "{{count}} minute",
    durationSingleLong_other: "{{count}} minutes",
    optionalTwists: "Optional twists",
    activeLabel: "Active {{mood}} quest: {{title}}",
    focusCard: "Focus quest card: {{title}}",
    closeFocusedCard: "Close focused quest card",
  },
  timer: {
    elapsed: "Elapsed time {{time}}",
    start: "Start quest timer",
    resume: "Resume quest timer",
    pause: "Pause quest timer",
    unavailable: "Quest timer unavailable",
    ready: "Ready",
    paused: "Paused",
    completeQuest: "Complete quest",
    completeAvailableIn:
      "You can complete this quest in <strong>{{time}}</strong>.",
    lessThanMinute: "less than a minute",
    completeOrCancel:
      "You need to finish this quest or cancel it by cutting the rope.",
    noRedRopes: "No cancellation ropes left. Complete this quest first.",
    coinsEarned: "You receive",
    coinsEarnedLabel: "You receive {{points}} coins",
    yourTime: "Your time",
    pullContinue: "Pull the timer to continue.",
    redRopesRemaining_one:
      "You have <strong>{{count}} rope left</strong> to cancel.",
    redRopesRemaining_other:
      "You have <strong>{{count}} ropes left</strong> to cancel.",
    noRopesRemaining: "You have <strong>no ropes left</strong> to cancel.",
    pullStart: "Pull the timer to start.",
    readyInstructions:
      // "Pull the timer to start.<br/>Minimum duration: <strong>{{time}}</strong>",
      "Pull the timer to start.",
    pullResume: "Pull the timer to resume.",
    pullPause: "Pull the timer to pause.",
    backToSelection: "Back to selection screen",
    backToSelectionTooltip: "This quest stays open.",
    cutStop: "Cut the rope to stop.",
  },
  profile: {
    title: "Your profile",
    pointsLabel: "{{points}} coins",
    points: "Coins",
    description: "Your coins, settings, and completed sidequests.",
    back: "Back to profile",
    yourSidequests: "Your sidequests",
    redRopes: "Cancellation ropes",
    owned: "Owned",
    buyRopeInline: "Buy rope",
    buyOneRope: "Buy 1",
    viewHistory: "View quest history",
    buy: "Buy",
    redRopesAvailable_one: "{{count}} rope available",
    redRopesAvailable_other: "{{count}} ropes available",
    buyRopes_one: "Buy {{count}} rope",
    buyRopes_other: "Buy {{count}} ropes",
    buyRopesLabel_one:
      "Buy {{count}} cancellation rope for {{points}} coins. {{available}} coins available.",
    buyRopesLabel_other:
      "Buy {{count}} cancellation ropes for {{points}} coins. {{available}} coins available.",
    statistics: "Statistics",
    completedQuests: "Completed quests",
    timePlayed: "Time played",
    timePlayedMinutes: "{{minutes}} min",
    timePlayedHours: "{{hours}}h {{minutes}}m",
    coinsCollected: "Coins collected",
    cancelledQuests: "Cancelled quests",
    repeatedQuests: "Repeated quests",
    favoriteMood: "Favorite mood",
    noFavoriteMood: "None yet",
    debugMode: "Developer Mode",
    debugModeDescription: "No minimum duration and cancelling is free",
    debugModeLabel: "Toggle local debug mode",
    debugModeInfoLabel: "About developer mode",
    debugModeOn: "On",
    debugModeOff: "Off",
    settings: "Settings",
    theme: "Theme",
    themeAuto: "Auto",
    themeLight: "Light",
    themeDark: "Dark",
    sound: "Sound",
    soundLabel: "Toggle sound",
  },
} as const;

type TranslationShape<T> = {
  [Key in keyof T]: T[Key] extends string ? string : TranslationShape<T[Key]>;
};

export const germanUi = {
  nav: {
    skipToContent: "Zum Inhalt springen",
    mainNavigation: "Hauptnavigation",
    about: "Info",
    spinLogo: "Sidequest-Logo drehen",
    profileLabel: "Dein Profil, {{points}} Münzen",
    points: "{{points}} Münzen",
    switchLanguage: "Zu {{language}} wechseln",
    english: "Englisch",
    german: "Deutsch",
    task: "Quest",
  },
  about: {
    title: "Willkommen bei sidesidequest.",
    description:
      "Eine kleine Starthilfe für Menschen mit zu vielen Videospielen.",
    stepsHeading: "In drei Schritten vom Aussuchen zum Spielen",
    step1: "Wähle, wie du dich beim Spielen fühlen möchtest",
    step2:
      "Such dir eine von drei Quests für deine Bibliothek oder ein beliebiges Spiel aus",
    step3: "Starte den Timer, schließe die Quest ab und sammle Münzen",
    mismatchHeading: "Die Aufgabe passt doch nicht?",
    mismatchBody:
      "Vor dem Start kannst du kostenlos zu den Karten zurück. Läuft der Timer schon, brichst du die Quest mit einem roten Seil ab.",
    difficultyBody:
      "Lies die ganze Aufgabe vor dem Start. Manche Quests brauchen einen Modus, Gegenstand, eine Mechanik oder einen ausreichend fortgeschrittenen Spielstand.",
    libraryHeading: "Deine Bibliothek, deine Quests",
    libraryBody:
      "Wähle aus der Starter-Sammlung oder füge selbst ein beliebiges Spiel hinzu. Spiele aus der Sammlung bekommen eigene kuratierte Quests und flexible Quests, die zu ihren Features passen.",
    libraryChoice:
      "Bei einer Reihe wählst du die Teile, die du wirklich spielst, damit Quests für einzelne Teile stimmen. Die Bibliothek kannst du später im Profil ändern. Karten ohne festes Spiel funktionieren weiterhin mit jeder Bibliothek.",
    sourcesHeading: "Woher kommen die Ideen?",
    sourcesBody:
      "Manche Quests haben mit Ideen angefangen, die Spieler auf Reddit geteilt haben. Ich prüfe die Idee, mache eine kleine Session daraus und schreib die sidequests selbst. Andere entstehen aus dem, was ein Spiel möglich macht.",
    sourcesButton: "Reddit-Quellen",
    sourcesTitle: "Reddit-Quellen",
    sourcesDescription:
      "Die Threads hinter meiner Recherche, nach Spiel sortiert. Bei jedem steht, was ich daraus mitgenommen haben.",
    sourcesBack: "Zurück zur Info",
    sourcesOpen: "Reddit-Thread öffnen",
    sourcesQuestNames: "Davon inspirierte Quests",
    sourcesResearchOnly: "Für die Hintergrundrecherche genutzt",
    sourcesLinkHint:
      "Links öffnen Reddit in einem neuen Tab. Die Originaltitel bleiben so, wie sie geschrieben wurden.",
    coinsHeading: "Was mache ich mit den Münzen?",
    coinEarning:
      "Je länger du an einer Quest sitzt, desto mehr Münzen gibt es dafür.",
    coinSpending:
      "Neue Karten und zusätzliche rote Seile kosten Münzen. Die Idee: etwas weniger aussuchen und etwas mehr spielen.",
    madeBy: "Von",
  },
  library: germanLibrary,
  history: {
    title: "Quest-Verlauf",
    description: "Deine abgeschlossenen Sidequests, die neuesten zuerst.",
    profileSummary_one: "{{count}} abgeschlossene Quest",
    profileSummary_other: "{{count}} abgeschlossene Quests",
    emptyTitle: "Noch keine Sidequest abgeschlossen",
    emptyBody: "Abgeschlossene Quests erscheinen hier mit Spiel und Ergebnis.",
    anyGame: "Beliebiges Spiel",
    mood: "Stimmung",
    duration: "Zeit",
    reward: "Belohnung",
    coins: "{{count}} Münzen",
  },
  task: {
    currentQuest: "Aktuelle Quest",
    chooseMoodQuest: "Wähle eine Quest für {{mood}}",
    selectMood: "Wähle deine Stimmung",
    choosePrefix: "Wähle eine",
    chooseSuffix: "-Sidequest",
    changeMood: "Stimmung ändern",
    newCardsLabel:
      "Neue Quest-Karten für {{cost}} Münzen. {{available}} Münzen verfügbar.",
    newCards: "Neue Karten",
    costsPoints: "kostet {{points}}",
    moodCards: "Stimmungskarten",
  },
  offers: {
    deckLabel: "Wähle eine von drei Quest-Karten",
    cardStatus: "Karte {{current}} von {{total}}: {{name}}. {{title}}",
    opening: "{{title}} wird geöffnet",
    hiddenQuest: "Quest",
    revealCard: "Verdeckte Quest-Karte {{number}} aufdecken",
    selectQuest: "{{name}} wählen: {{title}}",
  },
  arc: {
    choose: "Wählen",
    center: "Zentrieren",
    cardLabel: "{{action}}: {{title}}. {{subtitle}}",
    dragOrScroll: "Ziehen oder scrollen",
    status: "{{current}} von {{total}}: {{title}}. {{subtitle}}",
    noCards: "Keine Karten verfügbar",
  },
  quest: {
    minimumMinutes: "mindestens {{count}} Min.",
    suggestedMinutes: "{{count}} Min. empfohlen",
    durationRange: "{{minimum}}–{{suggested}} Min.",
    durationRangeLong: "{{minimum}}–{{suggested}} Minuten",
    durationSingle: "{{count}} Min.",
    durationSingleLong_one: "{{count}} Minute",
    durationSingleLong_other: "{{count}} Minuten",
    optionalTwists: "Optionale Spielvarianten",
    activeLabel: "Aktive Quest für {{mood}}: {{title}}",
    focusCard: "Quest-Karte fokussieren: {{title}}",
    closeFocusedCard: "Fokussierte Quest-Karte schließen",
  },
  timer: {
    elapsed: "Vergangene Zeit {{time}}",
    start: "Quest-Timer starten",
    resume: "Quest-Timer fortsetzen",
    pause: "Quest-Timer pausieren",
    unavailable: "Quest-Timer nicht verfügbar",
    ready: "Bereit",
    paused: "Pausiert",
    completeQuest: "Quest abschließen",
    completeAvailableIn:
      "Du kannst die Quest erst in <strong>{{time}}</strong> abschließen.",
    lessThanMinute: "weniger als einer Minute",
    completeOrCancel:
      "Du musst diese Quest abschließen oder sie durch Durchtrennen des Seils abbrechen.",
    noRedRopes: "Keine Abbruch-Seile mehr. Schließe zuerst diese Quest ab.",
    coinsEarned: "Du erhältst",
    coinsEarnedLabel: "Du erhältst {{points}} Münzen",
    yourTime: "Deine Zeit",
    pullContinue: "Zieh am Timer, um fortzufahren.",
    redRopesRemaining_one:
      "Du hast noch <strong>{{count}} Seil</strong> zum Abbrechen.",
    redRopesRemaining_other:
      "Du hast noch <strong>{{count}} Seile</strong> zum Abbrechen.",
    noRopesRemaining:
      "Du hast <strong>keine Seile</strong> mehr, um abzubrechen.",
    pullStart: "Ziehe am Timer, um zu starten.",
    readyInstructions:
      // "Zieh am Timer, um zu starten.<br/>Mindestlaufzeit: <strong>{{time}}</strong>",
      "Zieh am Timer, um zu starten.",
    pullResume: "Ziehe am Timer, um fortzufahren.",
    pullPause: "Ziehe am Timer, um zu pausieren.",
    backToSelection: "Zurück zur Auswahl",
    backToSelectionTooltip: "Die Quest bleibt offen.",
    cutStop: "Schneide das Seil durch zum Stoppen.",
  },
  profile: {
    title: "Dein Profil",
    pointsLabel: "{{points}} Münzen",
    points: "Münzen",
    description: "Deine Münzen, Einstellungen und abgeschlossenen Sidequests.",
    back: "Zurück zum Profil",
    yourSidequests: "Deine Sidequests",
    redRopes: "Abbruch-Seile",
    owned: "Im Besitz",
    buyRopeInline: "Seil kaufen",
    buyOneRope: "1x kaufen",
    viewHistory: "Quest-Verlauf ansehen",
    buy: "Kaufen",
    redRopesAvailable_one: "{{count}} Seil verfügbar",
    redRopesAvailable_other: "{{count}} Seile verfügbar",
    buyRopes_one: "{{count}} Seil kaufen",
    buyRopes_other: "{{count}} Seile kaufen",
    buyRopesLabel_one:
      "{{count}} Abbruch-Seil für {{points}} Münzen kaufen. {{available}} Münzen verfügbar.",
    buyRopesLabel_other:
      "{{count}} rote Seile für {{points}} Münzen kaufen. {{available}} Münzen verfügbar.",
    statistics: "Statistiken",
    completedQuests: "Abgeschlossene Quests",
    timePlayed: "Spielzeit",
    timePlayedMinutes: "{{minutes}} Min.",
    timePlayedHours: "{{hours}} Std {{minutes}} Min",
    coinsCollected: "Münzen gesammelt",
    cancelledQuests: "Abgebrochene Quests",
    repeatedQuests: "Wiederholte Quests",
    favoriteMood: "Lieblingsstimmung",
    noFavoriteMood: "Noch keine",
    debugMode: "Developer Mode",
    debugModeDescription: "Keine Mindestzeit und Abbrüche sind gratis",
    debugModeLabel: "Lokalen Debug-Modus umschalten",
    debugModeInfoLabel: "Über den Developer Mode",
    debugModeOn: "An",
    debugModeOff: "Aus",
    settings: "Einstellungen",
    theme: "Theme",
    themeAuto: "Auto",
    themeLight: "Hell",
    themeDark: "Dunkel",
    sound: "Sound",
    soundLabel: "Sound umschalten",
  },
} as const satisfies TranslationShape<typeof englishUi>;

export const germanMoods = {
  relax: {
    title: "Entspannung",
    subtitle: "Ich möchte bei etwas Vertrautem abschalten und zur Ruhe kommen",
  },
  explore: {
    title: "Entdeckung",
    subtitle: "Ich möchte ein Spiel entdecken, das mich noch überraschen kann",
  },
  progress: {
    title: "Fortschritt",
    subtitle: "Ich möchte endlich ein liegen gelassenes Spiel voranbringen",
  },
  create: {
    title: "Kreativität",
    subtitle: "Ich möchte etwas Eigenes erschaffen, das sich nach mir anfühlt",
  },
  challenge: {
    title: "Herausforderung",
    subtitle: "Ich möchte Widerstand spüren und sehen, was ich schaffen kann",
  },
  connect: {
    title: "Gemeinschaft",
    subtitle: "Ich möchte mich beim Spielen anderen Menschen verbunden fühlen",
  },
  nostalgic: {
    title: "Nostalgie",
    subtitle:
      "Ich möchte zu einem Spiel mit einer guten Erinnerung zurückkehren",
  },
  overwhelmed: {
    title: "Überforderung",
    subtitle: "Ich möchte spielen, kann aber gerade keine Auswahl vertragen",
  },
  restless: {
    title: "Unruhe",
    subtitle: "Ich habe zu viel Energie und muss sie in Bewegung bringen",
  },
  focused: {
    title: "Fokus",
    subtitle: "Ich möchte ganz in ein klares Ziel eintauchen",
  },
  curious: {
    title: "Neugier",
    subtitle: "Ich möchte etwas Unbekanntes ausprobieren und verstehen",
  },
  "low-energy": {
    title: "Wenig Energie",
    subtitle: "Ich möchte ohne viel Aufmerksamkeit oder Anstrengung spielen",
  },
} as const satisfies Record<string, Omit<MoodDefinition, "id">>;
