import type { MoodDefinition } from "../data/questTypes";

export const englishUi = {
  nav: {
    skipToContent: "Skip to content",
    mainNavigation: "Main navigation",
    about: "About",
    spinLogo: "Spin Sidequest logo",
    profileLabel: "Your profile, {{points}} coins",
    points: "{{points}} coins",
    switchLanguage: "Switch to {{language}}",
    english: "English",
    german: "German",
    task: "Task",
  },
  about: {
    title: "Welcome to sidesidequest.",
    description: "A small companion app for people with too many video games.",
    stepsHeading: "Three steps to your game",
    step1: "Choose a mood that fits",
    step2: "Pick a quest shaped around a game in your library",
    step3: "Complete the quest at your own pace and earn coins",
    mismatchHeading: "The quest isn't right for you?",
    mismatchBody: "Cut the red rope, draw a new card, and try another quest.",
    difficultyBody:
      "How difficult a quest ultimately is also depends on the game you choose.",
    libraryHeading: "Your library, your quests",
    libraryBody:
      "Choose from the curated games or add your own. Sidequest combines game-specific cards with universal quests that work across your collection.",
    coinsHeading: "What do I do with the coins?",
    coinEarning: "The longer you spend on a quest, the more coins you earn.",
    coinSpending:
      "New quests and cancelling a sidequest cost coins. To ease the agony of choice, sooner or later you will have to choose a quest that may not have appealed to you right away.",
    madeBy: "Made by",
  },
  library: {
    setupEyebrow: "Your game shelf",
    setupTitle: "Which games should your sidequests know?",
    setupDescription:
      "Start with the curated collection or add your own games. You can change this library any time from your profile.",
    curatedHeading: "Curated collection",
    curatedDescription:
      "Ready-made quests written specifically for these games.",
    customHeading: "Your own games",
    customDescription:
      "A short feature checklist matches reusable quests to any game you add.",
    addGame: "Add game",
    saveGame: "Save game",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Remove",
    untitledGame: "Untitled game",
    gameName: "Game name",
    gameNamePlaceholder: "e.g. Stardew Valley",
    gameIcon: "Genre icon",
    gameColor: "Color",
    iconChoice: "Use the {{icon}} icon",
    colorChoice: "Use the {{color}} color",
    capabilities: "What can you do in this game?",
    capabilitiesHint:
      "Select every feature that reliably exists. This creates the first quest match automatically.",
    reviewQuests: "Review matched quests",
    reviewQuestsHint:
      "Fine-tune the automatic match. These choices only affect this game.",
    questCount_one: "{{count}} quest",
    questCount_other: "{{count}} quests",
    capabilityCount_one: "{{count}} feature",
    capabilityCount_other: "{{count}} features",
    noCustomGames: "No custom games added yet.",
    setupSelection_one: "{{count}} game selected",
    setupSelection_other: "{{count}} games selected",
    startSidequests: "Start sidequests",
    drawerTitle: "Game library",
    drawerDescription: "Choose curated games and manage your custom games.",
    profileSummary: "Choose and configure your games",
    icons: {
      action: "action",
      adventure: "adventure",
      arcade: "arcade",
      building: "building",
      cards: "cards",
      cozy: "cozy",
      exploration: "exploration",
      fighting: "fighting",
      horror: "horror",
      multiplayer: "multiplayer",
      platformer: "platformer",
      puzzle: "puzzle",
      racing: "racing",
      rhythm: "rhythm",
      rpg: "role-playing",
      shooter: "shooter",
      simulation: "simulation",
      sports: "sports",
      strategy: "strategy",
      survival: "survival",
    },
    capabilityLabels: {
      "open-world": "Open world",
      "missions-or-levels": "Missions or levels",
      "rounds-or-matches": "Rounds or matches",
      combat: "Combat",
      "boss-fights": "Boss fights",
      stealth: "Stealth",
      "equipment-loadouts": "Equipment and loadouts",
      puzzles: "Puzzles",
      building: "Building",
      crafting: "Crafting",
      fishing: "Fishing",
      cooking: "Cooking",
      "farming-or-care": "Farming or care",
      "driving-or-racing": "Driving or racing",
      "advanced-traversal": "Advanced traversal",
      customization: "Customization",
      "photo-mode": "Photo mode",
      "online-teamplay": "Online teamplay",
      "local-multiplayer": "Local multiplayer",
      collectibles: "Collectibles",
      "choices-or-lore": "Choices or lore",
    },
  },
  history: {
    title: "Quest history",
    description: "Your completed sidequests, newest first.",
    profileSummary_one: "{{count}} completed quest",
    profileSummary_other: "{{count}} completed quests",
    emptyTitle: "No completed sidequests yet",
    emptyBody: "Completed quests will appear here with their game and result.",
    anyGame: "Any game",
    mood: "Mood",
    duration: "Time",
    reward: "Reward",
    coins: "{{count}} coins",
  },
  task: {
    currentQuest: "Current quest",
    chooseMoodQuest: "Choose a {{mood}} quest",
    selectMood: "Select your mood",
    choosePrefix: "Choose a",
    chooseSuffix: "sidequest",
    changeMood: "Change Mood",
    newCardsLabel:
      "Get new quest cards for {{cost}} coins. {{available}} coins available.",
    newCards: "New cards",
    costsPoints: "costs {{points}}",
    moodCards: "Mood cards",
  },
  offers: {
    deckLabel: "Choose one of three quest cards",
    cardStatus: "Card {{current}} of {{total}}: {{name}}. {{title}}",
    opening: "Opening {{title}}",
    hiddenQuest: "quest",
    revealCard: "Reveal hidden quest card {{number}}",
    selectQuest: "Select {{name}}: {{title}}",
  },
  arc: {
    choose: "Choose",
    center: "Center",
    cardLabel: "{{action}} {{title}}. {{subtitle}}",
    dragOrScroll: "Drag or Scroll",
    status: "{{current}} of {{total}}: {{title}}. {{subtitle}}",
    noCards: "No cards available",
  },
  quest: {
    minimumMinutes: "{{count}} min minimum",
    suggestedMinutes: "{{count}} min suggested",
    durationRange: "{{minimum}}–{{suggested}} min",
    durationRangeLong: "{{minimum}}–{{suggested}} minutes",
    durationSingle: "{{count}} min",
    durationSingleLong_one: "{{count}} minute",
    durationSingleLong_other: "{{count}} minutes",
    optionalTwists: "Optional twists",
    activeLabel: "Active {{mood}} quest: {{title}}",
    focusCard: "Focus quest card: {{title}}",
    closeFocusedCard: "Close focused quest card",
  },
  timer: {
    elapsed: "Elapsed time {{time}}",
    start: "Start quest timer",
    resume: "Resume quest timer",
    pause: "Pause quest timer",
    unavailable: "Quest timer unavailable",
    ready: "Ready",
    paused: "Paused",
    completeQuest: "Complete quest",
    completeAvailableIn:
      "You can complete this quest in <strong>{{time}}</strong>.",
    lessThanMinute: "less than a minute",
    completeOrCancel:
      "You need to finish this quest or cancel it by cutting the rope.",
    noRedRopes: "No cancellation ropes left. Complete this quest first.",
    coinsEarned: "You receive",
    coinsEarnedLabel: "You receive {{points}} coins",
    yourTime: "Your time",
    pullContinue: "Pull the timer to continue.",
    redRopesRemaining_one:
      "You have <strong>{{count}} rope left</strong> to cancel.",
    redRopesRemaining_other:
      "You have <strong>{{count}} ropes left</strong> to cancel.",
    noRopesRemaining: "You have <strong>no ropes left</strong> to cancel.",
    pullStart: "Pull the timer to start.",
    readyInstructions:
      // "Pull the timer to start.<br/>Minimum duration: <strong>{{time}}</strong>",
      "Pull the timer to start.",
    pullResume: "Pull the timer to resume.",
    pullPause: "Pull the timer to pause.",
    backToSelection: "Back to selection screen",
    backToSelectionTooltip: "This quest stays open.",
    cutStop: "Cut the rope to stop.",
  },
  profile: {
    title: "Your profile",
    pointsLabel: "{{points}} coins",
    points: "Coins",
    description: "Your coins, settings, and completed sidequests.",
    back: "Back to profile",
    yourSidequests: "Your sidequests",
    redRopes: "Cancellation ropes",
    owned: "Owned",
    buyRopeInline: "Buy rope",
    buy: "Buy",
    redRopesAvailable_one: "{{count}} rope available",
    redRopesAvailable_other: "{{count}} ropes available",
    buyRopes_one: "Buy {{count}} rope",
    buyRopes_other: "Buy {{count}} ropes",
    buyRopesLabel_one:
      "Buy {{count}} cancellation rope for {{points}} coins. {{available}} coins available.",
    buyRopesLabel_other:
      "Buy {{count}} cancellation ropes for {{points}} coins. {{available}} coins available.",
    statistics: "Statistics",
    completedQuests: "Completed quests",
    timePlayed: "Time played",
    timePlayedMinutes: "{{minutes}} min",
    timePlayedHours: "{{hours}}h {{minutes}}m",
    coinsCollected: "Coins collected",
    cancelledQuests: "Cancelled quests",
    repeatedQuests: "Repeated quests",
    favoriteMood: "Favorite mood",
    noFavoriteMood: "None yet",
    debugMode: "Debug mode",
    debugModeDescription: "No minimum duration and cancelling is free",
    debugModeLabel: "Toggle local debug mode",
    debugModeInfoLabel: "About developer mode",
    debugModeOn: "On",
    debugModeOff: "Off",
    settings: "Settings",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    sound: "Sound",
    soundLabel: "Toggle sound",
  },
} as const;

type TranslationShape<T> = {
  [Key in keyof T]: T[Key] extends string ? string : TranslationShape<T[Key]>;
};

export const germanUi = {
  nav: {
    skipToContent: "Zum Inhalt springen",
    mainNavigation: "Hauptnavigation",
    about: "Info",
    spinLogo: "Sidequest-Logo drehen",
    profileLabel: "Dein Profil, {{points}} Münzen",
    points: "{{points}} Münzen",
    switchLanguage: "Zu {{language}} wechseln",
    english: "Englisch",
    german: "Deutsch",
    task: "Quest",
  },
  about: {
    title: "Willkommen bei sidesidequest.",
    description:
      "Eine kleine Companion-App für Menschen mit zu vielen Videospielen.",
    stepsHeading: "In drei Schritten zu deinem Spiel",
    step1: "Wähle eine passende Stimmung",
    step2:
      "Such dir eine Quest aus, die zu einem Spiel in deiner Bibliothek passt",
    step3: "Schließe die Quest in deinem Tempo ab und verdiene Münzen",
    mismatchHeading: "Die Aufgabe passt doch nicht?",
    mismatchBody:
      "Schneide das rote Seil durch, ziehe eine neue Karte und probier eine andere Aufgabe aus.",
    difficultyBody:
      "Wie schwer eine Aufgabe am Ende ist, hängt auch von deinem gewählten Spiel ab.",
    libraryHeading: "Deine Bibliothek, deine Quests",
    libraryBody:
      "Wähle Spiele aus der kuratierten Sammlung oder füge eigene hinzu. Sidequest mischt spielspezifische Karten mit universellen Quests für deine ganze Sammlung.",
    coinsHeading: "Was mache ich mit den Münzen?",
    coinEarning:
      "Je länger du an einer Quest sitzt, desto mehr Münzen gibt es dafür.",
    coinSpending:
      "Neue Quests und der Abbruch einer sidequest kosten Münzen. Um die Qual der Wahl etwas zu dämpfen musst du dich früher oder später auch mal für eine Quest entscheiden, die dich vielleicht nicht sofort angesprochen hat.",
    madeBy: "Von",
  },
  library: {
    setupEyebrow: "Dein Spieleregal",
    setupTitle: "Welche Spiele sollen deine Sidequests kennen?",
    setupDescription:
      "Starte mit der kuratierten Sammlung oder füge eigene Spiele hinzu. Du kannst die Bibliothek jederzeit im Profil ändern.",
    curatedHeading: "Kuratierte Sammlung",
    curatedDescription:
      "Fertige Quests, die eigens für diese Spiele geschrieben wurden.",
    customHeading: "Deine eigenen Spiele",
    customDescription:
      "Eine kurze Feature-Auswahl ordnet jedem Spiel passende, wiederverwendbare Quests zu.",
    addGame: "Spiel hinzufügen",
    saveGame: "Spiel speichern",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    remove: "Entfernen",
    untitledGame: "Unbenanntes Spiel",
    gameName: "Spielname",
    gameNamePlaceholder: "z. B. Stardew Valley",
    gameIcon: "Genre-Icon",
    gameColor: "Farbe",
    iconChoice: "Icon {{icon}} verwenden",
    colorChoice: "Farbe {{color}} verwenden",
    capabilities: "Was kannst du in diesem Spiel tun?",
    capabilitiesHint:
      "Wähle alle Features, die zuverlässig vorhanden sind. Daraus entsteht automatisch die erste Quest-Auswahl.",
    reviewQuests: "Passende Quests prüfen",
    reviewQuestsHint:
      "Passe die automatische Auswahl an. Diese Änderungen gelten nur für dieses Spiel.",
    questCount_one: "{{count}} Quest",
    questCount_other: "{{count}} Quests",
    capabilityCount_one: "{{count}} Feature",
    capabilityCount_other: "{{count}} Features",
    noCustomGames: "Noch keine eigenen Spiele hinzugefügt.",
    setupSelection_one: "{{count}} Spiel ausgewählt",
    setupSelection_other: "{{count}} Spiele ausgewählt",
    startSidequests: "Sidequests starten",
    drawerTitle: "Spielebibliothek",
    drawerDescription:
      "Wähle kuratierte Spiele und verwalte deine eigenen Spiele.",
    profileSummary: "Spiele auswählen und einrichten",
    icons: {
      action: "Action",
      adventure: "Abenteuer",
      arcade: "Arcade",
      building: "Bauen",
      cards: "Karten",
      cozy: "Gemütlich",
      exploration: "Erkundung",
      fighting: "Kampfspiel",
      horror: "Horror",
      multiplayer: "Multiplayer",
      platformer: "Platformer",
      puzzle: "Rätsel",
      racing: "Rennspiel",
      rhythm: "Rhythmus",
      rpg: "Rollenspiel",
      shooter: "Shooter",
      simulation: "Simulation",
      sports: "Sport",
      strategy: "Strategie",
      survival: "Survival",
    },
    capabilityLabels: {
      "open-world": "Offene Welt",
      "missions-or-levels": "Missionen oder Level",
      "rounds-or-matches": "Runden oder Matches",
      combat: "Kampf",
      "boss-fights": "Bosskämpfe",
      stealth: "Schleichen",
      "equipment-loadouts": "Ausrüstung und Loadouts",
      puzzles: "Rätsel",
      building: "Bauen",
      crafting: "Herstellen",
      fishing: "Angeln",
      cooking: "Kochen",
      "farming-or-care": "Farmen oder Pflegen",
      "driving-or-racing": "Fahren oder Rennen",
      "advanced-traversal": "Erweiterte Fortbewegung",
      customization: "Anpassung",
      "photo-mode": "Fotomodus",
      "online-teamplay": "Online-Teamplay",
      "local-multiplayer": "Lokaler Multiplayer",
      collectibles: "Sammelobjekte",
      "choices-or-lore": "Entscheidungen oder Lore",
    },
  },
  history: {
    title: "Quest-Verlauf",
    description: "Deine abgeschlossenen Sidequests, die neuesten zuerst.",
    profileSummary_one: "{{count}} abgeschlossene Quest",
    profileSummary_other: "{{count}} abgeschlossene Quests",
    emptyTitle: "Noch keine Sidequest abgeschlossen",
    emptyBody:
      "Abgeschlossene Quests erscheinen hier mit Spiel und Ergebnis.",
    anyGame: "Beliebiges Spiel",
    mood: "Stimmung",
    duration: "Zeit",
    reward: "Belohnung",
    coins: "{{count}} Münzen",
  },
  task: {
    currentQuest: "Aktuelle Quest",
    chooseMoodQuest: "Wähle eine Quest für {{mood}}",
    selectMood: "Wähle deine Stimmung",
    choosePrefix: "Wähle eine",
    chooseSuffix: "-Sidequest",
    changeMood: "Stimmung ändern",
    newCardsLabel:
      "Neue Quest-Karten für {{cost}} Münzen. {{available}} Münzen verfügbar.",
    newCards: "Neue Karten",
    costsPoints: "kostet {{points}}",
    moodCards: "Stimmungskarten",
  },
  offers: {
    deckLabel: "Wähle eine von drei Quest-Karten",
    cardStatus: "Karte {{current}} von {{total}}: {{name}}. {{title}}",
    opening: "{{title}} wird geöffnet",
    hiddenQuest: "Quest",
    revealCard: "Verdeckte Quest-Karte {{number}} aufdecken",
    selectQuest: "{{name}} wählen: {{title}}",
  },
  arc: {
    choose: "Wählen",
    center: "Zentrieren",
    cardLabel: "{{action}}: {{title}}. {{subtitle}}",
    dragOrScroll: "Ziehen oder scrollen",
    status: "{{current}} von {{total}}: {{title}}. {{subtitle}}",
    noCards: "Keine Karten verfügbar",
  },
  quest: {
    minimumMinutes: "mindestens {{count}} Min.",
    suggestedMinutes: "{{count}} Min. empfohlen",
    durationRange: "{{minimum}}–{{suggested}} Min.",
    durationRangeLong: "{{minimum}}–{{suggested}} Minuten",
    durationSingle: "{{count}} Min.",
    durationSingleLong_one: "{{count}} Minute",
    durationSingleLong_other: "{{count}} Minuten",
    optionalTwists: "Optionale Spielvarianten",
    activeLabel: "Aktive Quest für {{mood}}: {{title}}",
    focusCard: "Quest-Karte fokussieren: {{title}}",
    closeFocusedCard: "Fokussierte Quest-Karte schließen",
  },
  timer: {
    elapsed: "Vergangene Zeit {{time}}",
    start: "Quest-Timer starten",
    resume: "Quest-Timer fortsetzen",
    pause: "Quest-Timer pausieren",
    unavailable: "Quest-Timer nicht verfügbar",
    ready: "Bereit",
    paused: "Pausiert",
    completeQuest: "Quest abschließen",
    completeAvailableIn:
      "Du kannst die Quest erst in <strong>{{time}}</strong> abschließen.",
    lessThanMinute: "weniger als einer Minute",
    completeOrCancel:
      "Du musst diese Quest abschließen oder sie durch Durchtrennen des Seils abbrechen.",
    noRedRopes: "Keine Abbruch-Seile mehr. Schließe zuerst diese Quest ab.",
    coinsEarned: "Du erhältst",
    coinsEarnedLabel: "Du erhältst {{points}} Münzen",
    yourTime: "Deine Zeit",
    pullContinue: "Zieh am Timer, um fortzufahren.",
    redRopesRemaining_one:
      "Du hast noch <strong>{{count}} Seil</strong> zum Abbrechen.",
    redRopesRemaining_other:
      "Du hast noch <strong>{{count}} Seile</strong> zum Abbrechen.",
    noRopesRemaining:
      "Du hast <strong>keine Seile</strong> mehr, um abzubrechen.",
    pullStart: "Ziehe am Timer, um zu starten.",
    readyInstructions:
      // "Zieh am Timer, um zu starten.<br/>Mindestlaufzeit: <strong>{{time}}</strong>",
      "Zieh am Timer, um zu starten.",
    pullResume: "Ziehe am Timer, um fortzufahren.",
    pullPause: "Ziehe am Timer, um zu pausieren.",
    backToSelection: "Zurück zur Auswahl",
    backToSelectionTooltip: "Die Quest bleibt offen.",
    cutStop: "Schneide das Seil durch zum Stoppen.",
  },
  profile: {
    title: "Dein Profil",
    pointsLabel: "{{points}} Münzen",
    points: "Münzen",
    description: "Deine Münzen, Einstellungen und abgeschlossenen Sidequests.",
    back: "Zurück zum Profil",
    yourSidequests: "Deine Sidequests",
    redRopes: "Abbruch-Seile",
    owned: "Im Besitz",
    buyRopeInline: "Seil kaufen",
    buy: "Kaufen",
    redRopesAvailable_one: "{{count}} Seil verfügbar",
    redRopesAvailable_other: "{{count}} Seile verfügbar",
    buyRopes_one: "{{count}} Seil kaufen",
    buyRopes_other: "{{count}} Seile kaufen",
    buyRopesLabel_one:
      "{{count}} Abbruch-Seil für {{points}} Münzen kaufen. {{available}} Münzen verfügbar.",
    buyRopesLabel_other:
      "{{count}} rote Seile für {{points}} Münzen kaufen. {{available}} Münzen verfügbar.",
    statistics: "Statistiken",
    completedQuests: "Abgeschlossene Quests",
    timePlayed: "Spielzeit",
    timePlayedMinutes: "{{minutes}} Min.",
    timePlayedHours: "{{hours}} Std {{minutes}} Min",
    coinsCollected: "Münzen gesammelt",
    cancelledQuests: "Abgebrochene Quests",
    repeatedQuests: "Wiederholte Quests",
    favoriteMood: "Lieblingsstimmung",
    noFavoriteMood: "Noch keine",
    debugMode: "Debug-Modus",
    debugModeDescription: "Keine Mindestzeit und Abbrüche sind gratis",
    debugModeLabel: "Lokalen Debug-Modus umschalten",
    debugModeInfoLabel: "Über den Developer Mode",
    debugModeOn: "An",
    debugModeOff: "Aus",
    settings: "Einstellungen",
    theme: "Theme",
    themeLight: "Hell",
    themeDark: "Dunkel",
    sound: "Sound",
    soundLabel: "Sound umschalten",
  },
} as const satisfies TranslationShape<typeof englishUi>;

export const germanMoods = {
  relax: {
    title: "Entspannung",
    subtitle: "Ich möchte bei etwas Vertrautem abschalten und zur Ruhe kommen",
  },
  explore: {
    title: "Entdeckung",
    subtitle: "Ich möchte ein Spiel entdecken, das mich noch überraschen kann",
  },
  progress: {
    title: "Fortschritt",
    subtitle: "Ich möchte endlich ein liegen gelassenes Spiel voranbringen",
  },
  create: {
    title: "Kreativität",
    subtitle: "Ich möchte etwas Eigenes erschaffen, das sich nach mir anfühlt",
  },
  challenge: {
    title: "Herausforderung",
    subtitle: "Ich möchte Widerstand spüren und sehen, was ich schaffen kann",
  },
  connect: {
    title: "Gemeinschaft",
    subtitle: "Ich möchte mich beim Spielen anderen Menschen verbunden fühlen",
  },
  nostalgic: {
    title: "Nostalgie",
    subtitle:
      "Ich möchte zu einem Spiel mit einer guten Erinnerung zurückkehren",
  },
  overwhelmed: {
    title: "Überforderung",
    subtitle: "Ich möchte spielen, kann aber gerade keine Auswahl vertragen",
  },
  restless: {
    title: "Unruhe",
    subtitle: "Ich habe zu viel Energie und muss sie in Bewegung bringen",
  },
  focused: {
    title: "Fokus",
    subtitle: "Ich möchte ganz in ein klares Ziel eintauchen",
  },
  curious: {
    title: "Neugier",
    subtitle: "Ich möchte etwas Unbekanntes ausprobieren und verstehen",
  },
  "low-energy": {
    title: "Wenig Energie",
    subtitle: "Ich möchte ohne viel Aufmerksamkeit oder Anstrengung spielen",
  },
} as const satisfies Record<string, Omit<MoodDefinition, "id">>;
